In [61]:
import pandas as pd
import numpy as np
import glob 

path = "C:\\Users\\dmehri\\Documents\\DATA\\Qmatic Predictive Modelling\\"

#df = pd.read_csv(path + "QMATIC.csv")

print "Reading data..."
i=0
all_data = pd.DataFrame()
for f in glob.glob("C:\Users\dmehri\Documents\DATA\Qmatic Predictive Modelling\data\*.csv"):
    i+=1
    print i
    dfAppend = pd.read_csv(f)
    #get rid of Westchester
    all_data = all_data.append(dfAppend,ignore_index=True)


df = all_data.copy()


#df = df.drop('HOUR', 1)
#df = df.drop('MINUTE', 1)
#df = df.drop('SECONDS', 1)
df = df.drop('Staff User Name', 1)
#df = df.drop('CUSTOMER NAME', 1)
#df = df.drop('Customer ID', 1)
df = df.drop('ISN_DOB_BIS_LICENSE', 1)
df = df.drop('L_BUS_NAME', 1)
df = df.drop('TICKET_ID', 1)
#df = df.drop('DELIVERED_SERVICE', 1)
#df = df.drop('Service Category', 1)


print "Cleaning data..."
col_names = sorted(list(df.columns.values))

for i in range(0, len(col_names)):
    df[col_names[i]] = df[col_names[i]].astype(str)
for i in range(0, len(col_names)):
    df[col_names[i]] = df[col_names[i]].map(str.strip)

df["Date"] = df["MONTH"] + "-" + df["DAY"] + "-" + df["YEAR"]

df['Date'] = pd.to_datetime(df['Date'])

df["Date"] = df["Date"].apply(lambda x: x.date())


df["StaffName"] = df["STAFF FIRST_NAME"] + " " + df["STAFF LAST_NAME"]


print "Remove bad dates..."


removeDates = ["1-4-2019",
              "20160301",
              "20170222",
               "20170223",
               "20170224",
               "20170322",
                "20170323",
                "20170419",
                "20170420",
                "20170421",
                "20170526",
                "20170530",
                "20170626",
                "20170627",
                "20170628",
                "20170629",
                "20170630",
                "20170801",
                "20170802",
                "20170803",
                "20170804",
                "20170918",
                "20180130",
                "20180122",
                "20180116",
                "20180117",
                "20180724",
                "20180809",
                "20180810"]
              

from dateutil import parser

for i in range(0, len(removeDates)):
    removeDates[i] = parser.parse(removeDates[i])
    removeDates[i] = removeDates[i].date()
    #d = parser.parse(d)
    #d = d.date()
    #print d


print "Remove bad dates"
print "len before drop", len(df)
df = df[~df['Date'].isin(removeDates)]
print "len after drop", len(df)


#REMOVE EARLY DATES WHERE WORKERS WERE GETTING USED TO QMATIC SYSTEM
start_date = str(10) + '-' + str(1) + '-' + str(2016)
#from dateutil import parser
start_date = parser.parse(start_date)
start_date = start_date.date()

mask = (df['Date'] >= start_date)

df = df.loc[mask]

df = df.reset_index(drop=True)

print "len after final drop", len(df)


print "DONE"

Reading data...
1
2
3
4
5
Cleaning data...
Remove bad dates...
Remove bad dates
len before drop 2005013
len after drop 1960797
len after final drop 1629398
DONE

In [62]:
df

,NAME,YEAR,MONTH,DAY,HOUR,MINUTE,STAFF FIRST_NAME,STAFF LAST_NAME,CUSTOMER NAME,Customer ID,Service Category,Unit,WAITING_TIME,VISIT_KEY,Date,StaffName
0,Manhattan Central 4th 5th 6th,2016,10,3,8,30,Brendan,Small,JOHNJR MASTROPIERO,959760207,PL-FSC-License Renewals,6th-Plumber / Fire Suppression Contractor,2649,544436,2016-10-03,Brendan Small
1,Manhattan Borough,2016,10,3,8,31,Joann,Grimaldi,Victor Hernandez,X001150,Fast App,Fast App,24,544234,2016-10-03,Joann Grimaldi
2,Manhattan Borough,2016,10,3,8,31,Judith,Gonzalez,Steven Ruotolo,X003063,Application Processing,Application Processing,66,544236,2016-10-03,Judith Gonzalez
3,Queens,2016,10,3,8,31,Selina,Self,Lanette Simon,X004467,Fast App,Fast App,272,544287,2016-10-03,Selina Self
4,Manhattan Central 4th 5th 6th,2016,10,3,8,31,Pamela,Franklin,Howard Trueger,X004033,Permit Renewal,5th-Permit Renewal,1789,544510,2016-10-03,Pamela Franklin
5,Manhattan Borough,2016,10,3,8,32,Rosario,Lopez,Ramrattan Samlal,X002146,Application Processing,Application Processing,82,544239,2016-10-03,Rosario Lopez
6,Manhattan Borough,2016,10,3,8,32,Joann,Grimaldi,Ting Ye,X004141,Fast App,Fast App,334,544243,2016-10-03,Joann Grimaldi
7,Bronx,2016,10,3,8,32,Geraldine,Flowers,DARLYN ALVAREZ,N11373,Records,Records,2,544232,2016-10-03,Geraldine Flowers
8,Manhattan Central 4th 5th 6th,2016,10,3,8,32,Melissa,Zelaya,Joan Gonzalez,X001145,LAA Unit Drop-Offs,5th-LAA Unit Drop-Offs,1713,544343,2016-10-03,Melissa Zelaya
9,Queens,2016,10,3,8,32,Christal,Hopkins,Joseph Luna,X004281,Application Processing,Application Processing,1311,544311,2016-10-03,Christal Hopkins
10,Queens,2016,10,3,8,32,Brenda,Lindo,Muzaffar Zia,X003889,Application Processing,Application Processing,730,544285,2016-10-03,Brenda Lindo
11,Queens,2016,10,3,8,32,Bhadresh,Patel,Muzaffar Zia,X003889,Fee Estimator,Fee Estimator,332,544252,2016-10-03,Bhadresh Patel
12,Manhattan Borough,2016,10,3,8,33,Judith,Gonzalez,Christine Cramer,X002297,Application Processing,Application Processing,565,544309,2016-10-03,Judith Gonzalez
13,Manhattan Central 4th 5th 6th,2016,10,3,8,33,Jessica,Toro,Michael Montesanto,X001654,Rep - AEU Services,5th-AEU Representatives for Respondents,1455,544382,2016-10-03,Jessica Toro
14,Manhattan Central 4th 5th 6th,2016,10,3,8,33,Jessica,Toro,Najwa Duke,X006443,Rep - AEU Services,5th-AEU Representatives for Respondents,2609,544498,2016-10-03,Jessica Toro
15,Queens,2016,10,3,8,33,Selina,Self,Parminder Kataria,X002932,Fast App,Fast App,2116,544470,2016-10-03,Selina Self
16,Bronx,2016,10,3,8,33,Lenore,Rolls,Leslie McKenzie,X001179,Application Processing,Application Processing,1,544240,2016-10-03,Lenore Rolls
17,Manhattan Central 4th 5th 6th,2016,10,3,8,33,Jessica,Toro,Cynthia Perez,X006014,Rep - AEU Services,5th-AEU Representatives for Respondents,2220,544425,2016-10-03,Jessica Toro
18,Queens,2016,10,3,8,33,Christal,Hopkins,Mark Koutmanis,X001395,Application Processing,Application Processing,1561,544323,2016-10-03,Christal Hopkins
19,Queens,2016,10,3,8,33,Claribel,Abreu,Parminder Kataria,X002932,Application Processing,Application Processing,1558,544357,2016-10-03,Claribel Abreu
20,Queens,2016,10,3,8,33,Joan,Saccente,Mark Koutmanis,X001395,Cert of Occupancy,Cert of Occupancy,441,544290,2016-10-03,Joan Saccente
21,Manhattan Borough,2016,10,3,8,33,Thelma,Gadsden,Benedict Itwaria,X002145,Application Processing,Application Processing,686,544286,2016-10-03,Thelma Gadsden
22,Manhattan Borough,2016,10,3,8,34,David,Martin,Victor Hernandez,X001150,Application Processing,Application Processing,730,544280,2016-10-03,David Martin
23,Staten Island,2016,10,3,8,34,Deshaunda,Thomas,macie andrze falger,0,Records,Records,2,544233,2016-10-03,Deshaunda Thomas
24,Queens,2016,10,3,8,34,Jahmar,Chin,JOSEPH SHERRY,A11107,Prof Priority App Processing,Prof Priority App Processing,226,544253,2016-10-03,Jahmar Chin
25,Manhattan Borough,2016,10,3,8,34,Joann,Grimaldi,Brian Gateson,X001218,Fast App,Fast App,395,544259,2016-10-03,Joann Grimaldi
26,Queens,2016,10,3,8,34,Joan,Saccente,JOSEPH SHERRY,A11107,Cert of Occupancy,Cert of Occupancy,1266,544292,2016-10-03,Joan Saccente
27,Manhattan Borough,2016,10,3,8,34,Rosario,Lopez,Ting Ye,X004141,Application Processing,Application Processing,957,544390,2016-10-03,Rosario Lopez
28,Manhattan Central 4th 5th 6th,2016,10,3,8,34,Brendan,Small,DANIEL ABBATE,537735000,CS-Applying for New License/Registration,6th-Construction Superintendent,3426,544757,2016-10-03,Brendan Small
29,Manhattan Central 4th 5th 6th,2016,10,3,8,34,Dawn,Summerson,"S,S HARRIPERSAUD",353231004,Rep - AEU Services,5th-AEU Representatives for Respondents,3204,544541,2016-10-03,Dawn Summerson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1629368,Brooklyn,2018,12,31,15,2,Starrasia,Payne,Benje Larico,X003911,Construction Development,Construction Development,501,2238423,2018-12-31,Starrasia Payne
1629369,Manhattan Borough,2018,12,31,15,3,Rondel,Scipio,Lita Lynch,X001166,Application Processing,Application Processing,206,2238417,2018-12-31,Rondel Scipio
1629370,Queens,2018,12,31,15,6,Selina,Self,H. O.,0,Express Cashier,Express Cashier,102,2238425,2018-12-31,Selina Self
1629371,Brooklyn,2018,12,31,15,7,Minyon,Rhodes,Edward U,0,Records,Records,434,2238440,2018-12-31,Minyon Rhodes
1629372,Manhattan Central 1st,2018,12,31,15,7,Artur,Aronov,TZUCHUN CHEN,559882114,1st-REP-AEU Inquiries,1st-AEU Representatives for Respondents,421,2238433,2018-12-31,Artur Aronov
1629373,Staten Island,2018,12,31,15,10,Antigone,Hawkins,Nesia Amar,X007182,Application Processing,Application Processing,1,2238476,2018-12-31,Antigone Hawkins
1629374,Queens,2018,12,31,15,10,Selina,Self,Azeezan Toolsee,0,Express Cashier,Express Cashier,45,2238439,2018-12-31,Selina Self
1629375,Manhattan Borough,2018,12,31,15,13,Teisha,Russell,Lloyd Noel,X002884,Cert of Occupancy,Cert of Occupancy,0,2238438,2018-12-31,Teisha Russell
1629376,Brooklyn,2018,12,31,15,13,Sainath,Dasma,Julio Guadalupe,X001780,Fee Estimator,Fee Estimator,6,2238451,2018-12-31,Sainath Dasma
1629377,Brooklyn,2018,12,31,15,13,Shanayer,Crawley,Abraham Lebovits,X002577,Cert of Occupancy,Cert of Occupancy,169,2238444,2018-12-31,Shanayer Crawley
1629378,Brooklyn,2018,12,31,15,13,Shanayer,Crawley,Lionel Loh,X006522,Cert of Occupancy,Cert of Occupancy,265,2238449,2018-12-31,Shanayer Crawley
1629379,Brooklyn,2018,12,31,15,13,Tajmal,Walker,Abraham Lebovits,X002577,Application Processing,Application Processing,896,2238475,2018-12-31,Tajmal Walker
1629380,Queens,2018,12,31,15,14,Selina,Self,Ellen Stern,X002234,Express Cashier,Express Cashier,225,2238446,2018-12-31,Selina Self
1629381,Queens,2018,12,31,15,14,Bhadresh,Patel,Ellen Stern,X002234,Fee Estimator,Fee Estimator,159,2238460,2018-12-31,Bhadresh Patel
1629382,Manhattan Borough,2018,12,31,15,16,Devon,Adams,Lloyd Noel,X002884,Records,Records,0,2238471,2018-12-31,Devon Adams
1629383,Manhattan Central 1st,2018,12,31,15,17,Melba,Rogers,Viney Da,X001638,1st-REP-AEU Drop-Off,1st-AEU Representatives for Respondents,67,2238447,2018-12-31,Melba Rogers
1629384,Brooklyn,2018,12,31,15,20,Shanayer,Crawley,Mitchell Tischler,X003686,Cert of Occupancy,Cert of Occupancy,5,2238452,2018-12-31,Shanayer Crawley
1629385,Queens,2018,12,31,15,20,Jahmar,Chin,Ellen Stern,X002234,Application Processing,Application Processing,38,2238455,2018-12-31,Jahmar Chin
1629386,Manhattan Borough,2018,12,31,15,23,Teisha,Russell,Brian Sina,X005701,Cert of Occupancy,Cert of Occupancy,0,2238453,2018-12-31,Teisha Russell
1629387,Brooklyn,2018,12,31,15,23,Shanayer,Crawley,Leila Reynoso,X001825,Cert of Occupancy,Cert of Occupancy,534,2238464,2018-12-31,Shanayer Crawley
1629388,Queens,2018,12,31,15,24,Cathey,Jacques,Aylin zabski,0,Construction Enforcement,Construction Enforcement,0,2238459,2018-12-31,Cathey Jacques
1629389,Queens,2018,12,31,15,25,Jahmar,Chin,Yun Zhen Zeng-Posner,X002718,Application Processing,Application Processing,72,2238456,2018-12-31,Jahmar Chin
1629390,Brooklyn,2018,12,31,15,27,Shanayer,Crawley,Morton Mays,X001705,Application Processing,Application Processing,436,2238470,2018-12-31,Shanayer Crawley
1629391,Queens,2018,12,31,15,28,Lateefah,Bell,nieto ray,0,Plumbing Development,Plumbing Development,32,2238465,2018-12-31,Lateefah Bell
1629392,Brooklyn,2018,12,31,15,29,Mark,Levitas,Phillip Glauber,X006369,Application Processing,Application Processing,850,2238473,2018-12-31,Mark Levitas
1629393,Manhattan Borough,2018,12,31,15,29,Sharon,Weems-Wilborn,Brian Sina,X005701,Express Cashier,Express Cashier,110,2238466,2018-12-31,Sharon Weems-Wilborn
1629394,Brooklyn,2018,12,31,15,29,Diane,Brown Rivers,Mitchell Tischler,X003686,Application Processing,Application Processing,829,2238472,2018-12-31,Diane Brown Rivers
1629395,Brooklyn,2018,12,31,15,30,Diane,Brown Rivers,Madelyn Santana,X003921,Application Processing,Application Processing,1342,2238474,2018-12-31,Diane Brown Rivers
1629396,Manhattan Borough,2018,12,31,15,31,Sharon,Weems-Wilborn,Yoel Mittelman,X007178,Application Processing,Application Processing,320,2238467,2018-12-31,Sharon Weems-Wilborn
1629397,Manhattan Central 1st,2018,12,31,15,45,Declan,Daly,KALMAN ZIMMERMAN,840617170,1st-RESP-AEU Inquiries,1st-Administrative Enforcement Respondents,351,2238477,2018-12-31,Declan Daly

# ALL DATA: EACH ROW IS A TRANSACTION

CREATE DATETIME

In [5]:
df["DateTime"] = df["Date"].astype(str)
df["DateTime"] = df["DateTime"] + " " + df["HOUR"] + ":" + df["MINUTE"]
df["DateTime"] = pd.to_datetime(df["DateTime"])
df["Time"] = df["DateTime"].apply( lambda d : d.time() )

REMOVE BAD DATES

CREATE TARGET VARIABLE

In [23]:
#CREATE A DICTIONARY OF DATES AND AVG WAITING TIME
#MEAN
pd.set_option('chained_assignment', None)
df2 = df.copy()
df2 = df2[["Date", "WAITING_TIME"]]
df2.WAITING_TIME = df2.WAITING_TIME.astype(int)
df2 = (df2.groupby('Date').agg({'WAITING_TIME':'mean'}).reset_index().rename(columns={'WAITING_TIME':'WAITING_TIME_mean', 'StaffName':"StaffCount"}) )
df2 = df2.sort_values(by = 'WAITING_TIME_mean', ascending=False).reset_index(drop=True)

#df2 = df2.sort_values(by = 'Date', ascending=True).reset_index(drop=True)

#MEDIAN
df3 = df.copy()
df3 = df3[["Date", "WAITING_TIME"]]
df3.WAITING_TIME = df3.WAITING_TIME.astype(int)
df3 = (df3.groupby('Date').agg({'WAITING_TIME':'median'}).reset_index().rename(columns={'WAITING_TIME':'WAITING_TIME_median'}) )

df2 = pd.merge(df2, df3, how='left', on=['Date'])

#CREATE TARGET
df2["Target"] = 0
count=1
for i in range(0, len(df2)):
    if df2.WAITING_TIME_mean[i] >= 1500:
        df2["Target"][i] = 1
        count+=1
        
print "target number", count
print "target number percent", round( float(count)/len(df2), 3)


df2 = df2[["Date", "Target"]]

target number 102
target number percent 0.199

In [24]:
df2

           Date  Target
0    2017-11-08       1
1    2018-11-07       1
2    2018-11-13       1
3    2017-09-29       1
4    2017-11-13       1
5    2016-11-09       1
6    2018-12-13       1
7    2017-11-03       1
8    2017-11-09       1
9    2017-11-15       1
10   2017-10-25       1
11   2018-10-10       1
12   2017-11-29       1
13   2018-12-19       1
14   2017-02-14       1
15   2017-10-11       1
16   2017-10-10       1
17   2018-12-11       1
18   2017-09-19       1
19   2017-10-27       1
20   2018-12-20       1
21   2017-09-15       1
22   2018-12-04       1
23   2017-11-01       1
24   2018-11-08       1
25   2018-11-20       1
26   2018-12-18       1
27   2017-10-02       1
28   2017-09-27       1
29   2017-10-18       1
..          ...     ...
482  2018-07-06       0
483  2017-12-26       0
484  2018-01-09       0
485  2018-04-23       0
486  2018-05-29       0
487  2018-04-25       0
488  2018-03-08       0
489  2018-05-22       0
490  2017-01-09       0
491  2018-01-03       0
492  2016-12-27       0
493  2018-09-11       0
494  2018-03-22       0
495  2018-03-01       0
496  2018-11-23       0
497  2018-01-02       0
498  2018-07-05       0
499  2018-01-05       0
500  2018-09-04       0
501  2017-01-04       0
502  2018-07-16       0
503  2018-04-16       0
504  2017-11-24       0
505  2017-01-03       0
506  2016-11-25       0
507  2018-09-10       0
508  2017-03-14       0
509  2018-04-02       0
510  2018-01-04       0
511  2017-02-09       0

[512 rows x 2 columns]

In [ ]:
servCat = sorted(list(set(df["Service Category"].tolist() ) ))

#print len(servCat)

#servCat

In [ ]:
#servCat = sorted(list(set(df["Service Category"].tolist() )))

#print servCat

In [ ]:
#delService = sorted(list(set(df["DELIVERED_SERVICE"].tolist() )))

#print delService

In [ ]:
#unit = sorted(list(set(df["Unit"].tolist() )))
#print unit

# AGGREGATED TO THE DAY

###  DO PROPER STAFF COUNT AVERAGE, redo service category and delivered service to exclude those with a lot of zeros

### WAITING TIME

In [149]:
#MEAN
pd.set_option('chained_assignment', None)

df2 = df.copy()

df2 = df2[["Date", "WAITING_TIME"]]

df2.WAITING_TIME = df2.WAITING_TIME.astype(int)

df2 = (df2.groupby('Date').agg({'WAITING_TIME':'mean'}).reset_index().rename(columns={'WAITING_TIME':'WAITING_TIME_mean', 'StaffName':"StaffCount"}) )

df2 = df2.sort_values(by = 'WAITING_TIME_mean', ascending=False).reset_index(drop=True)

#df2 = df2.sort_values(by = 'Date', ascending=True).reset_index(drop=True)

#MEDIAN
df3 = df.copy()
df3 = df3[["Date", "WAITING_TIME"]]
df3.WAITING_TIME = df3.WAITING_TIME.astype(int)
df3 = (df3.groupby('Date').agg({'WAITING_TIME':'median'}).reset_index().rename(columns={'WAITING_TIME':'WAITING_TIME_median'}) )

df2 = pd.merge(df2, df3, how='left', on=['Date'])

### STAFF HOURS

In [150]:
sh = pd.read_csv("C:\\Users\\dmehri\\Documents\\DATA\\Qmatic Predictive Modelling\\data\\Staff Service Time\\QMATIC Staff Service Time.csv")

sh['FULL_DATE'] = pd.to_datetime(sh['FULL_DATE'])
sh['FULL_DATE'] = sh['FULL_DATE'].apply(lambda x: x.date())

sh["SERVING_TIME"] = sh["SERVING_TIME"].astype(int)
sh["IDLE_TIME"] = sh["IDLE_TIME"].astype(int)

sh = sh[["FULL_DATE", "SERVING_TIME", "IDLE_TIME"]]

sh = sh.groupby(['FULL_DATE']).sum()

sh = sh.add_suffix('').reset_index()

sh = sh.rename(columns={'FULL_DATE': 'Date'})

df2 = pd.merge(df2, sh, how='left', on=['Date'])

In [151]:
df2

,Date,WAITING_TIME_mean,WAITING_TIME_median,SERVING_TIME,IDLE_TIME
0,2017-11-08,2845.981924,1459.0,1276745,1296357
1,2018-11-07,2400.458296,1532.0,1277485,1164240
2,2018-11-13,2295.207389,1161.0,1166616,1220938
3,2017-09-29,2106.476298,781.5,884649,1117141
4,2017-11-13,2069.472864,1123.0,1148183,1245409
5,2016-11-09,2052.120125,938.5,1350571,2048696
6,2018-12-13,2026.362245,678.0,1011451,1245801
7,2017-11-03,1976.095678,830.0,973304,1249199
8,2017-11-09,1962.120408,1095.0,1235559,1292014
9,2017-11-15,1922.976477,914.0,1134381,1304583
10,2017-10-25,1890.258939,771.0,1033354,1385476
11,2018-10-10,1882.295294,896.0,1046191,1119823
12,2017-11-29,1865.742908,929.0,1094778,1274031
13,2018-12-19,1842.445163,665.5,1070542,1284058
14,2017-02-14,1810.109442,811.5,1139155,1956626
15,2017-10-11,1807.992849,882.5,1101460,1259109
16,2017-10-10,1801.489374,793.0,1123092,1258298
17,2018-12-11,1795.111660,756.0,937333,1186407
18,2017-09-19,1793.692385,705.0,919230,1157038
19,2017-10-27,1792.481598,674.0,968699,1232883
20,2018-12-20,1786.379916,714.0,990373,1167756
21,2017-09-15,1775.756804,866.0,1053485,1220707
22,2018-12-04,1775.119740,847.5,1054844,1276342
23,2017-11-01,1774.094939,695.0,1049868,1241822
24,2018-11-08,1765.792847,892.0,1090125,1213545
25,2018-11-20,1762.778431,827.0,1113004,1293803
26,2018-12-18,1743.626011,627.5,909101,1169714
27,2017-10-02,1741.760504,558.0,908121,1246899
28,2017-09-27,1739.589247,674.5,916817,1602398
29,2017-10-18,1725.490754,823.0,1053623,1302631
...,...,...,...,...,...
482,2018-07-06,905.987047,476.0,908343,1297787
483,2017-12-26,899.757391,340.5,751172,1339892
484,2018-01-09,898.826667,449.0,943653,1386280
485,2018-04-23,887.635561,552.5,972247,1393294
486,2018-05-29,884.465354,489.0,874357,1350889
487,2018-04-25,877.416919,487.5,983098,1364761
488,2018-03-08,874.242514,383.0,905781,1428731
489,2018-05-22,867.657834,514.0,1023779,1467428
490,2017-01-09,861.325868,468.0,896687,2031784
491,2018-01-03,860.777118,446.0,975024,1484207
492,2016-12-27,859.418097,345.5,882802,2416463
493,2018-09-11,858.999639,467.0,836575,1359713
494,2018-03-22,858.976704,380.0,832122,1235536
495,2018-03-01,853.123718,496.0,965742,1426796
496,2018-11-23,842.791607,437.0,516511,1156345
497,2018-01-02,838.334964,360.5,786160,1343039
498,2018-07-05,825.234777,427.5,863585,1373014
499,2018-01-05,823.048027,357.0,666938,1355463
500,2018-09-04,818.793955,404.0,797641,1427144
501,2017-01-04,796.734917,443.0,1005023,2144535
502,2018-07-16,764.114351,428.5,939855,1277878
503,2018-04-16,749.454866,326.5,820555,1535528
504,2017-11-24,692.785221,276.0,551309,1360355
505,2017-01-03,690.382377,311.5,788343,2222028
506,2016-11-25,688.996180,203.0,578843,1820580
507,2018-09-10,667.995812,322.0,765105,1332835
508,2017-03-14,621.512987,265.0,137110,713000
509,2018-04-02,613.767392,352.0,778260,1343194
510,2018-01-04,610.597039,290.0,448399,980197
511,2017-02-09,572.663603,306.5,480477,1810383

### ADD FALL AS SEASON

In [152]:
j = 0
df2["SeasonFall"] = 0
for i in range(0, len(df2)):
    #print df2["Date"][i].month
    
    if (df2["Date"][i].month == 9 or df2["Date"][i].month == 10 or df2["Date"][i].month == 11):
        df2["SeasonFall"][i] = 1

### NUMBER OF UNIQUE CUSTOMERS

In [153]:
df["CUSTOMER NAME"] = df["CUSTOMER NAME"].astype(str).map(str.lower).map(str.strip)
df3 = df.groupby("Date").agg({"CUSTOMER NAME": pd.Series.nunique})

df3 = df3.add_suffix('').reset_index()
df2 = pd.merge(df2, df3, how='left', on=['Date'])

df2 = df2.rename(columns={'CUSTOMER NAME': '#CUSTOMERS'})

In [154]:
df2

,Date,WAITING_TIME_mean,WAITING_TIME_median,SERVING_TIME,IDLE_TIME,SeasonFall,#CUSTOMERS
0,2017-11-08,2845.981924,1459.0,1276745,1296357,1,1556
1,2018-11-07,2400.458296,1532.0,1277485,1164240,1,1533
2,2018-11-13,2295.207389,1161.0,1166616,1220938,1,1386
3,2017-09-29,2106.476298,781.5,884649,1117141,1,982
4,2017-11-13,2069.472864,1123.0,1148183,1245409,1,1363
5,2016-11-09,2052.120125,938.5,1350571,2048696,1,1377
6,2018-12-13,2026.362245,678.0,1011451,1245801,0,1157
7,2017-11-03,1976.095678,830.0,973304,1249199,1,1190
8,2017-11-09,1962.120408,1095.0,1235559,1292014,1,1510
9,2017-11-15,1922.976477,914.0,1134381,1304583,1,1274
10,2017-10-25,1890.258939,771.0,1033354,1385476,1,1274
11,2018-10-10,1882.295294,896.0,1046191,1119823,1,1239
12,2017-11-29,1865.742908,929.0,1094778,1274031,1,1198
13,2018-12-19,1842.445163,665.5,1070542,1284058,0,1169
14,2017-02-14,1810.109442,811.5,1139155,1956626,0,1172
15,2017-10-11,1807.992849,882.5,1101460,1259109,1,1210
16,2017-10-10,1801.489374,793.0,1123092,1258298,1,1232
17,2018-12-11,1795.111660,756.0,937333,1186407,0,1163
18,2017-09-19,1793.692385,705.0,919230,1157038,1,1049
19,2017-10-27,1792.481598,674.0,968699,1232883,1,1177
20,2018-12-20,1786.379916,714.0,990373,1167756,0,1182
21,2017-09-15,1775.756804,866.0,1053485,1220707,1,1144
22,2018-12-04,1775.119740,847.5,1054844,1276342,0,1223
23,2017-11-01,1774.094939,695.0,1049868,1241822,1,1117
24,2018-11-08,1765.792847,892.0,1090125,1213545,1,1305
25,2018-11-20,1762.778431,827.0,1113004,1293803,1,1242
26,2018-12-18,1743.626011,627.5,909101,1169714,0,1118
27,2017-10-02,1741.760504,558.0,908121,1246899,1,1091
28,2017-09-27,1739.589247,674.5,916817,1602398,1,1010
29,2017-10-18,1725.490754,823.0,1053623,1302631,1,1233
...,...,...,...,...,...,...,...
482,2018-07-06,905.987047,476.0,908343,1297787,0,1050
483,2017-12-26,899.757391,340.5,751172,1339892,0,851
484,2018-01-09,898.826667,449.0,943653,1386280,0,1090
485,2018-04-23,887.635561,552.5,972247,1393294,0,1147
486,2018-05-29,884.465354,489.0,874357,1350889,0,989
487,2018-04-25,877.416919,487.5,983098,1364761,0,1152
488,2018-03-08,874.242514,383.0,905781,1428731,0,1027
489,2018-05-22,867.657834,514.0,1023779,1467428,0,1126
490,2017-01-09,861.325868,468.0,896687,2031784,0,968
491,2018-01-03,860.777118,446.0,975024,1484207,0,1074
492,2016-12-27,859.418097,345.5,882802,2416463,0,944
493,2018-09-11,858.999639,467.0,836575,1359713,1,1023
494,2018-03-22,858.976704,380.0,832122,1235536,0,1008
495,2018-03-01,853.123718,496.0,965742,1426796,0,1152
496,2018-11-23,842.791607,437.0,516511,1156345,1,558
497,2018-01-02,838.334964,360.5,786160,1343039,0,810
498,2018-07-05,825.234777,427.5,863585,1373014,0,1021
499,2018-01-05,823.048027,357.0,666938,1355463,0,753
500,2018-09-04,818.793955,404.0,797641,1427144,1,972
501,2017-01-04,796.734917,443.0,1005023,2144535,0,1142
502,2018-07-16,764.114351,428.5,939855,1277878,0,1111
503,2018-04-16,749.454866,326.5,820555,1535528,0,992
504,2017-11-24,692.785221,276.0,551309,1360355,1,570
505,2017-01-03,690.382377,311.5,788343,2222028,0,893
506,2016-11-25,688.996180,203.0,578843,1820580,1,522
507,2018-09-10,667.995812,322.0,765105,1332835,1,840
508,2017-03-14,621.512987,265.0,137110,713000,0,79
509,2018-04-02,613.767392,352.0,778260,1343194,0,836
510,2018-01-04,610.597039,290.0,448399,980197,0,427
511,2017-02-09,572.663603,306.5,480477,1810383,0,410

### HOLIDAYS

In [74]:
"""
from dateutil import parser

import datetime

#from datetime import date
#from dateutil.relativedelta import relativedelta
#from dateutil import parser

holidays = ["01-02-2017", "2-20-2017","5-29-2017", "7-04-2017", "9-04-2017", "10-09-2017", "11-07-2017", "11-12-2017",
           "11-23-2017", "11-25-2017",
           "1-01-2018", "1-15-2018", "2-19-2018", "5-28-2018", "7-04-2018", "9-03-2018", "10-08-2018", "11-06-2018",
           "11-12-2018", "11-22-2018", "12-25-2018"]

d = holidays[0]

#print d

d = parser.parse(d)
d = d.date()

#print d

d = d + datetime.timedelta(days=1)

#print d


df2["HolidayBefore"] = 0

for i in range(0, len(holidays)):
    d = holidays[i]
    d = parser.parse(d)
    d = d.date()
    d = d + datetime.timedelta(days=1)
    for j in range(0, len(df2)):
        if (d.day == df2["Date"][j].day and d.month == df2["Date"][j].month and d.year == df2["Date"][j].year):
            print df2["Date"][j].month,df2["Date"][j].day, df2["Date"][j].year
            df2["HolidayBefore"][j] = 1
        
"""

'\nfrom dateutil import parser\n\nimport datetime\n\n#from datetime import date\n#from dateutil.relativedelta import relativedelta\n#from dateutil import parser\n\nholidays = ["01-02-2017", "2-20-2017","5-29-2017", "7-04-2017", "9-04-2017", "10-09-2017", "11-07-2017", "11-12-2017",\n           "11-23-2017", "11-25-2017",\n           "1-01-2018", "1-15-2018", "2-19-2018", "5-28-2018", "7-04-2018", "9-03-2018", "10-08-2018", "11-06-2018",\n           "11-12-2018", "11-22-2018", "12-25-2018"]\n\nd = holidays[0]\n\n#print d\n\nd = parser.parse(d)\nd = d.date()\n\n#print d\n\nd = d + datetime.timedelta(days=1)\n\n#print d\n\n\ndf2["HolidayBefore"] = 0\n\nfor i in range(0, len(holidays)):\n    d = holidays[i]\n    d = parser.parse(d)\n    d = d.date()\n    d = d + datetime.timedelta(days=1)\n    for j in range(0, len(df2)):\n        if (d.day == df2["Date"][j].day and d.month == df2["Date"][j].month and d.year == df2["Date"][j].year):\n            print df2["Date"][j].month,df2["Date"][j].day, df2["Date"][j].year\n            df2["HolidayBefore"][j] = 1\n        \n'

In [75]:
#df2.to_csv(path + "test.csv", index=False)

### TRANSACTION TIME

In [76]:
"""
df3 = df.copy()

df3 = df3[["Date", "TRANSACTION_TIME"]]

df3.TRANSACTION_TIME = df3.TRANSACTION_TIME.astype(int)

df3 = (df3.groupby('Date').agg({'TRANSACTION_TIME':'mean'}).reset_index().rename(columns={'TRANSACTION_TIME':'TRANSACTION_TIME_mean'}) )

#df3 = df3.sort_values(by = 'TRANSACTION_TIME_mean', ascending=False).reset_index(drop=True)

df2 = pd.merge(df2, df3, how='left', on=['Date'])

"""

'\ndf3 = df.copy()\n\ndf3 = df3[["Date", "TRANSACTION_TIME"]]\n\ndf3.TRANSACTION_TIME = df3.TRANSACTION_TIME.astype(int)\n\ndf3 = (df3.groupby(\'Date\').agg({\'TRANSACTION_TIME\':\'mean\'}).reset_index().rename(columns={\'TRANSACTION_TIME\':\'TRANSACTION_TIME_mean\'}) )\n\n#df3 = df3.sort_values(by = \'TRANSACTION_TIME_mean\', ascending=False).reset_index(drop=True)\n\ndf2 = pd.merge(df2, df3, how=\'left\', on=[\'Date\'])\n\n'

In [77]:
df2.head(2)

         Date  WAITING_TIME_mean  WAITING_TIME_median  SeasonFall  #CUSTOMERS
0  2017-11-08        2845.981924               1459.0           1        1556
1  2018-11-07        2400.458296               1532.0           1        1533

### COUNT NUMBER OF STAFF AND TRANSACTIONS

In [155]:
df3 = df[["Date", "StaffName"]]
df3["Count"] = 1

df3 = df3.groupby(['Date', 'StaffName']).sum()

df3 = df3.add_suffix('').reset_index()

date_list = sorted(list(set(df3["Date"].tolist() )))

staff_count = []

for i in range(0, len(date_list)):
    df4 = df3[df3["Date"] == date_list[i]]
    num_staff = len(df4)
    num_trans = df4["Count"].sum()
    #print num_staff
    #print num_trans
    #print df4
    
    staff_count.append([date_list[i], num_staff, num_trans])
    
dfsc = pd.DataFrame(staff_count, columns=('Date', 'StaffCount', 'Trans'))


#merge

df2 = pd.merge(df2, dfsc, how='left', on=['Date'])

In [ ]:
#df3.to_csv(path + "delivered service.csv", index=False)

In [156]:
df2

,Date,WAITING_TIME_mean,WAITING_TIME_median,SERVING_TIME,IDLE_TIME,SeasonFall,#CUSTOMERS,StaffCount,Trans
0,2017-11-08,2845.981924,1459.0,1276745,1296357,1,1556,135,4481
1,2018-11-07,2400.458296,1532.0,1277485,1164240,1,1533,135,4460
2,2018-11-13,2295.207389,1161.0,1166616,1220938,1,1386,128,3708
3,2017-09-29,2106.476298,781.5,884649,1117141,1,982,111,2658
4,2017-11-13,2069.472864,1123.0,1148183,1245409,1,1363,132,3851
5,2016-11-09,2052.120125,938.5,1350571,2048696,1,1377,144,4154
6,2018-12-13,2026.362245,678.0,1011451,1245801,0,1157,120,3136
7,2017-11-03,1976.095678,830.0,973304,1249199,1,1190,119,3031
8,2017-11-09,1962.120408,1095.0,1235559,1292014,1,1510,138,4410
9,2017-11-15,1922.976477,914.0,1134381,1304583,1,1274,130,3571
10,2017-10-25,1890.258939,771.0,1033354,1385476,1,1274,128,3580
11,2018-10-10,1882.295294,896.0,1046191,1119823,1,1239,126,3400
12,2017-11-29,1865.742908,929.0,1094778,1274031,1,1198,125,3384
13,2018-12-19,1842.445163,665.5,1070542,1284058,0,1169,127,3246
14,2017-02-14,1810.109442,811.5,1139155,1956626,0,1172,130,3262
15,2017-10-11,1807.992849,882.5,1101460,1259109,1,1210,129,3496
16,2017-10-10,1801.489374,793.0,1123092,1258298,1,1232,131,3482
17,2018-12-11,1795.111660,756.0,937333,1186407,0,1163,127,3036
18,2017-09-19,1793.692385,705.0,919230,1157038,1,1049,118,2981
19,2017-10-27,1792.481598,674.0,968699,1232883,1,1177,124,3179
20,2018-12-20,1786.379916,714.0,990373,1167756,0,1182,129,3077
21,2017-09-15,1775.756804,866.0,1053485,1220707,1,1144,124,3417
22,2018-12-04,1775.119740,847.5,1054844,1276342,0,1223,130,3232
23,2017-11-01,1774.094939,695.0,1049868,1241822,1,1117,130,3023
24,2018-11-08,1765.792847,892.0,1090125,1213545,1,1305,133,3635
25,2018-11-20,1762.778431,827.0,1113004,1293803,1,1242,131,3403
26,2018-12-18,1743.626011,627.5,909101,1169714,0,1118,125,2968
27,2017-10-02,1741.760504,558.0,908121,1246899,1,1091,121,2856
28,2017-09-27,1739.589247,674.5,916817,1602398,1,1010,114,2790
29,2017-10-18,1725.490754,823.0,1053623,1302631,1,1233,132,3515
...,...,...,...,...,...,...,...,...,...
482,2018-07-06,905.987047,476.0,908343,1297787,0,1050,130,3011
483,2017-12-26,899.757391,340.5,751172,1339892,0,851,107,2300
484,2018-01-09,898.826667,449.0,943653,1386280,0,1090,136,3225
485,2018-04-23,887.635561,552.5,972247,1393294,0,1147,123,3172
486,2018-05-29,884.465354,489.0,874357,1350889,0,989,122,2742
487,2018-04-25,877.416919,487.5,983098,1364761,0,1152,118,3298
488,2018-03-08,874.242514,383.0,905781,1428731,0,1027,123,3039
489,2018-05-22,867.657834,514.0,1023779,1467428,0,1126,131,3472
490,2017-01-09,861.325868,468.0,896687,2031784,0,968,125,2679
491,2018-01-03,860.777118,446.0,975024,1484207,0,1074,128,3033
492,2016-12-27,859.418097,345.5,882802,2416463,0,944,113,2564
493,2018-09-11,858.999639,467.0,836575,1359713,1,1023,117,2773
494,2018-03-22,858.976704,380.0,832122,1235536,0,1008,119,2876
495,2018-03-01,853.123718,496.0,965742,1426796,0,1152,134,3217
496,2018-11-23,842.791607,437.0,516511,1156345,1,558,94,1406
497,2018-01-02,838.334964,360.5,786160,1343039,0,810,120,2248
498,2018-07-05,825.234777,427.5,863585,1373014,0,1021,124,2956
499,2018-01-05,823.048027,357.0,666938,1355463,0,753,113,2103
500,2018-09-04,818.793955,404.0,797641,1427144,1,972,123,2713
501,2017-01-04,796.734917,443.0,1005023,2144535,0,1142,134,3199
502,2018-07-16,764.114351,428.5,939855,1277878,0,1111,124,3052
503,2018-04-16,749.454866,326.5,820555,1535528,0,992,120,2836
504,2017-11-24,692.785221,276.0,551309,1360355,1,570,96,1448
505,2017-01-03,690.382377,311.5,788343,2222028,0,893,118,2474
506,2016-11-25,688.996180,203.0,578843,1820580,1,522,90,1309
507,2018-09-10,667.995812,322.0,765105,1332835,1,840,126,2388
508,2017-03-14,621.512987,265.0,137110,713000,0,79,35,154
509,2018-04-02,613.767392,352.0,778260,1343194,0,836,124,2343
510,2018-01-04,610.597039,290.0,448399,980197,0,427,86,1216
511,2017-02-09,572.663603,306.5,480477,1810383,0,410,87,1088

### INSERT WEATHER DATA

In [157]:
w = pd.read_csv(path + "Weather Data.csv")

w["NAME"] = w["NAME"].astype(str)
w["NAME"] = w["NAME"].map(str.upper)

w = w[w.NAME.str.contains("CENTRAL PARK") == True].reset_index(drop=True)

w = w[["DATE", "PRCP", "SNOW", "TMAX", "TMIN"]]

w["SNOW"] = w["SNOW"].fillna(0)
w["PRCP"] = w["PRCP"].fillna(0)

w["TAVE"] = (w.TMAX + w.TMIN)/2

w["DATE"] = pd.to_datetime(w["DATE"])
w["DATE"] = w["DATE"].apply(lambda x: x.date())

w = w.rename(columns={'DATE': 'Date'})

#MERGE WITH DF2
df2 = pd.merge(df2, w, how='left', on=['Date'])

In [158]:
#CONVERT SNOW AND PRCP TO DUMMIES
for i in range(0, len(df2)):
    if df2["SNOW"][i] > 0:
        df2["SNOW"][i] = 1
    if df2["PRCP"][i] > 0:
        df2["PRCP"][i] = 1

In [82]:
#w.to_csv(path + "Weather Data Central Park.csv", index=False)

In [83]:
#df2["PRCP_Flag"] = 0
#df2["SNOW_Flag"] = 0
#for i in range(0, len(df2)):
#    if df2["PRCP"][i] > 0:
#        df2["PRCP_Flag"][i] = 1
#    if df2["SNOW"][i] > 0:
#        df2["SNOW_Flag"][i] = 1

In [84]:
df2

,Date,WAITING_TIME_mean,WAITING_TIME_median,SeasonFall,#CUSTOMERS,StaffCount,Trans,PRCP,SNOW,TMAX,TMIN,TAVE
0,2017-11-08,2845.981924,1459.0,1,1556,135,4481,0.0,0.0,49.0,39.0,44.0
1,2018-11-07,2400.458296,1532.0,1,1533,135,4460,0.0,0.0,62.0,51.0,56.5
2,2018-11-13,2295.207389,1161.0,1,1386,128,3708,1.0,0.0,50.0,43.0,46.5
3,2017-09-29,2106.476298,781.5,1,982,111,2658,0.0,0.0,68.0,55.0,61.5
4,2017-11-13,2069.472864,1123.0,1,1363,132,3851,1.0,0.0,47.0,39.0,43.0
5,2016-11-09,2052.120125,938.5,1,1377,144,4154,1.0,0.0,59.0,49.0,54.0
6,2018-12-13,2026.362245,678.0,0,1157,120,3136,0.0,0.0,42.0,35.0,38.5
7,2017-11-03,1976.095678,830.0,1,1190,119,3031,0.0,0.0,74.0,51.0,62.5
8,2017-11-09,1962.120408,1095.0,1,1510,138,4410,0.0,0.0,55.0,39.0,47.0
9,2017-11-15,1922.976477,914.0,1,1274,130,3571,0.0,0.0,51.0,37.0,44.0
10,2017-10-25,1890.258939,771.0,1,1274,128,3580,0.0,0.0,67.0,57.0,62.0
11,2018-10-10,1882.295294,896.0,1,1239,126,3400,0.0,0.0,80.0,71.0,75.5
12,2017-11-29,1865.742908,929.0,1,1198,125,3384,0.0,0.0,63.0,42.0,52.5
13,2018-12-19,1842.445163,665.5,0,1169,127,3246,0.0,0.0,43.0,28.0,35.5
14,2017-02-14,1810.109442,811.5,0,1172,130,3262,0.0,0.0,41.0,28.0,34.5
15,2017-10-11,1807.992849,882.5,1,1210,129,3496,1.0,0.0,77.0,60.0,68.5
16,2017-10-10,1801.489374,793.0,1,1232,131,3482,0.0,0.0,81.0,66.0,73.5
17,2018-12-11,1795.111660,756.0,0,1163,127,3036,0.0,0.0,43.0,31.0,37.0
18,2017-09-19,1793.692385,705.0,1,1049,118,2981,1.0,0.0,78.0,69.0,73.5
19,2017-10-27,1792.481598,674.0,1,1177,124,3179,0.0,0.0,62.0,47.0,54.5
20,2018-12-20,1786.379916,714.0,0,1182,129,3077,0.0,0.0,54.0,35.0,44.5
21,2017-09-15,1775.756804,866.0,1,1144,124,3417,0.0,0.0,81.0,67.0,74.0
22,2018-12-04,1775.119740,847.5,0,1223,130,3232,0.0,0.0,46.0,31.0,38.5
23,2017-11-01,1774.094939,695.0,1,1117,130,3023,0.0,0.0,59.0,43.0,51.0
24,2018-11-08,1765.792847,892.0,1,1305,133,3635,0.0,0.0,56.0,45.0,50.5
25,2018-11-20,1762.778431,827.0,1,1242,131,3403,0.0,0.0,47.0,39.0,43.0
26,2018-12-18,1743.626011,627.5,0,1118,125,2968,0.0,0.0,40.0,29.0,34.5
27,2017-10-02,1741.760504,558.0,1,1091,121,2856,0.0,0.0,73.0,52.0,62.5
28,2017-09-27,1739.589247,674.5,1,1010,114,2790,0.0,0.0,87.0,69.0,78.0
29,2017-10-18,1725.490754,823.0,1,1233,132,3515,0.0,0.0,72.0,50.0,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...
482,2018-07-06,905.987047,476.0,0,1050,130,3011,1.0,0.0,80.0,69.0,74.5
483,2017-12-26,899.757391,340.5,0,851,107,2300,0.0,0.0,28.0,23.0,25.5
484,2018-01-09,898.826667,449.0,0,1090,136,3225,0.0,0.0,44.0,30.0,37.0
485,2018-04-23,887.635561,552.5,0,1147,123,3172,0.0,0.0,68.0,46.0,57.0
486,2018-05-29,884.465354,489.0,0,989,122,2742,0.0,0.0,89.0,63.0,76.0
487,2018-04-25,877.416919,487.5,0,1152,118,3298,1.0,0.0,60.0,52.0,56.0
488,2018-03-08,874.242514,383.0,0,1027,123,3039,0.0,0.0,39.0,33.0,36.0
489,2018-05-22,867.657834,514.0,0,1126,131,3472,1.0,0.0,68.0,55.0,61.5
490,2017-01-09,861.325868,468.0,0,968,125,2679,0.0,0.0,23.0,14.0,18.5
491,2018-01-03,860.777118,446.0,0,1074,128,3033,0.0,0.0,30.0,16.0,23.0
492,2016-12-27,859.418097,345.5,0,944,113,2564,0.0,0.0,60.0,40.0,50.0
493,2018-09-11,858.999639,467.0,1,1023,117,2773,1.0,0.0,74.0,62.0,68.0
494,2018-03-22,858.976704,380.0,0,1008,119,2876,1.0,1.0,50.0,32.0,41.0
495,2018-03-01,853.123718,496.0,0,1152,134,3217,1.0,0.0,60.0,44.0,52.0
496,2018-11-23,842.791607,437.0,1,558,94,1406,0.0,0.0,32.0,15.0,23.5
497,2018-01-02,838.334964,360.5,0,810,120,2248,0.0,0.0,26.0,13.0,19.5
498,2018-07-05,825.234777,427.5,0,1021,124,2956,0.0,0.0,90.0,76.0,83.0
499,2018-01-05,823.048027,357.0,0,753,113,2103,0.0,0.0,19.0,9.0,14.0
500,2018-09-04,818.793955,404.0,1,972,123,2713,0.0,0.0,92.0,77.0,84.5
501,2017-01-04,796.734917,443.0,0,1142,134,3199,0.0,0.0,52.0,34.0,43.0
502,2018-07-16,764.114351,428.5,0,1111,124,3052,0.0,0.0,90.0,75.0,82.5
503,2018-04-16,749.454866,326.5,0,992,120,2836,1.0,0.0,60.0,39.0,49.5
504,2017-11-24,692.785221,276.0,1,570,96,1448,0.0,0.0,50.0,35.0,42.5
505,2017-01-03,690.382377,311.5,0,893,118,2474,1.0,0.0,43.0,39.0,41.0
506,2016-11-25,688.996180,203.0,1,522,90,1309,1.0,0.0,54.0,45.0,49.5
507,2018-09-10,667.995812,322.0,1,840,126,2388,1.0,0.0,64.0,54.0,59.0
508,2017-03-14,621.512987,265.0,0,79,35,154,1.0,1.0,32.0,21.0,26.5
509,2018-04-02,613.767392,352.0,0,836,124,2343,1.0,1.0,43.0,33.0,38.0
510,2018-01-04,610.597039,290.0,0,427,86,1216,1.0,1.0,29.0,19.0,24.0
511,2017-02-09,572.663603,306.5,0,410,87,1088,1.0,1.0,44.0,19.0,31.5

In [ ]:
#w.to_csv(path + "test.csv", index=False)

In [ ]:
#df2.to_csv(path + "test.csv", index=False)

### REMOVE OUTLIERS

In [159]:
#number of trans > 1000
#staff count > 40
print "len before drop outliers", len(df2)

df2 = df2[df2["Trans"] > 1000]
df2 = df2[df2["StaffCount"] > 90].reset_index(drop=True)
df2 = df2[df2["WAITING_TIME_mean"] < 4000].reset_index(drop=True)
df2 = df2.sort_values(by = 'Date', ascending=True).reset_index(drop=True)

print "len after drop outliers", len(df2)

len before drop outliers 512

In [160]:
df2

,Date,WAITING_TIME_mean,WAITING_TIME_median,SERVING_TIME,IDLE_TIME,SeasonFall,#CUSTOMERS,StaffCount,Trans,PRCP,SNOW,TMAX,TMIN,TAVE
0,2016-10-03,1402.766485,594.0,1085333,1797083,1,977,126,2745,0.0,0.0,72.0,60.0,66.0
1,2016-10-04,1608.710671,666.0,3016194,4214952,1,929,119,2371,0.0,0.0,69.0,60.0,64.5
2,2016-10-05,1363.989637,709.0,1466052,3841504,1,830,124,2123,0.0,0.0,67.0,53.0,60.0
3,2016-10-06,1548.287252,793.0,903961,1629441,1,1117,128,2973,0.0,0.0,73.0,55.0,64.0
4,2016-10-07,1362.754694,612.0,1294825,1710081,1,1158,125,3355,0.0,0.0,75.0,57.0,66.0
5,2016-10-11,1698.428266,835.0,1569910,2642844,1,1091,134,2802,0.0,0.0,63.0,46.0,54.5
6,2016-10-12,1159.869386,535.0,864970,1780717,1,973,123,2427,0.0,0.0,66.0,53.0,59.5
7,2016-10-13,1524.265592,747.0,1126039,1929345,1,1205,137,3351,0.0,0.0,67.0,53.0,60.0
8,2016-10-14,1641.643924,713.0,1514061,3891612,1,1181,135,3415,0.0,0.0,62.0,47.0,54.5
9,2016-10-17,1449.208651,581.0,1060196,1772317,1,1070,121,2751,0.0,0.0,81.0,63.0,72.0
10,2016-10-18,1347.635408,641.0,1143652,1720066,1,1214,143,3423,0.0,0.0,81.0,67.0,74.0
11,2016-10-19,1516.164955,556.5,1268273,2051380,1,1163,128,3310,0.0,0.0,85.0,65.0,75.0
12,2016-10-20,1293.847840,717.5,1294260,3143692,1,1138,131,3194,0.0,0.0,70.0,62.0,66.0
13,2016-10-21,1714.826632,837.0,1410275,2650619,1,1106,132,3034,1.0,0.0,69.0,57.0,63.0
14,2016-10-24,1293.852921,575.0,1077490,1672260,1,1076,122,2978,0.0,0.0,62.0,47.0,54.5
15,2016-10-25,1341.936937,577.5,1209116,1906537,1,1181,137,3330,0.0,0.0,52.0,43.0,47.5
16,2016-10-26,1302.165340,494.0,1179670,2041439,1,1173,139,3266,0.0,0.0,51.0,38.0,44.5
17,2016-10-27,1530.535438,613.0,1176138,2138475,1,1202,135,3485,1.0,0.0,55.0,40.0,47.5
18,2016-10-28,1376.379720,643.0,1135124,2004484,1,1182,131,3284,0.0,0.0,51.0,42.0,46.5
19,2016-10-31,1031.448522,439.0,1022786,2139494,1,1057,133,2807,0.0,0.0,54.0,44.0,49.0
20,2016-11-01,1227.227594,580.0,1154476,1797169,1,1195,137,3392,0.0,0.0,58.0,40.0,49.0
21,2016-11-02,1289.398322,541.0,1187065,1894628,1,1217,136,3457,0.0,0.0,70.0,54.0,62.0
22,2016-11-03,1678.797577,545.0,1133340,1751557,1,1201,132,3384,0.0,0.0,72.0,57.0,64.5
23,2016-11-04,1696.713376,661.5,1160054,1951990,1,1226,130,3454,0.0,0.0,61.0,47.0,54.0
24,2016-11-07,999.277328,486.0,1189990,2082959,1,1214,127,3458,0.0,0.0,53.0,41.0,47.0
25,2016-11-09,2052.120125,938.5,1350571,2048696,1,1377,144,4154,1.0,0.0,59.0,49.0,54.0
26,2016-11-10,1695.765852,903.0,1372383,1926745,1,1364,135,4053,0.0,0.0,56.0,40.0,48.0
27,2016-11-14,1564.238876,813.0,1254929,1894650,1,1330,138,4023,0.0,0.0,62.0,46.0,54.0
28,2016-11-15,1349.379675,787.5,1239517,2057745,1,1204,134,3690,1.0,0.0,56.0,47.0,51.5
29,2016-11-16,1687.357576,713.0,1335674,1921003,1,1340,136,3795,0.0,0.0,61.0,45.0,53.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2018-11-16,1104.730044,611.5,860433,1256972,1,1044,124,2756,1.0,0.0,45.0,34.0,39.5
476,2018-11-19,1375.559929,710.0,1026088,1332609,1,1255,137,3379,0.0,0.0,50.0,41.0,45.5
477,2018-11-20,1762.778431,827.0,1113004,1293803,1,1242,131,3403,0.0,0.0,47.0,39.0,43.0
478,2018-11-21,1609.501129,862.0,1001231,1183912,1,1150,129,3099,0.0,0.0,44.0,27.0,35.5
479,2018-11-23,842.791607,437.0,516511,1156345,1,558,94,1406,0.0,0.0,32.0,15.0,23.5
480,2018-11-26,1051.694251,556.0,758742,1364360,1,1024,128,2731,1.0,0.0,53.0,45.0,49.0
481,2018-11-27,1420.867848,684.0,970324,1184020,1,1159,125,3216,1.0,0.0,45.0,37.0,41.0
482,2018-11-28,1234.641577,747.0,1024227,1277462,1,1212,133,3348,0.0,0.0,42.0,36.0,39.0
483,2018-11-29,1127.441632,651.0,992657,1298248,1,1236,133,3358,0.0,0.0,46.0,38.0,42.0
484,2018-11-30,1216.827714,645.5,931232,1115149,1,1100,126,2966,1.0,0.0,43.0,38.0,40.5
485,2018-12-03,1434.221248,725.0,984143,1103347,0,1176,125,3078,0.0,0.0,55.0,46.0,50.5
486,2018-12-04,1775.119740,847.5,1054844,1276342,0,1223,130,3232,0.0,0.0,46.0,31.0,38.5
487,2018-12-05,1607.037512,855.0,954348,1284185,0,1199,126,3119,0.0,0.0,37.0,28.0,32.5
488,2018-12-06,1556.371753,579.0,943434,1282307,0,1150,128,3080,0.0,0.0,40.0,30.0,35.0
489,2018-12-07,1331.167974,602.0,960872,1129155,0,1154,129,3060,0.0,0.0,40.0,29.0,34.5
490,2018-12-10,1264.566005,617.0,937928,1338739,0,1102,127,2871,0.0,0.0,41.0,30.0,35.5
491,2018-12-11,1795.111660,756.0,937333,1186407,0,1163,127,3036,0.0,0.0,43.0,31.0,37.0
492,2018-12-12,1551.491558,785.0,984158,1322685,0,1155,136,3139,0.0,0.0,42.0,34.0,38.0
493,2018-12-13,2026.362245,678.0,1011451,1245801,0,1157,120,3136,0.0,0.0,42.0,35.0,38.5
494,2018-12-14,1383.718226,642.0,861987,1203155,0,1098,124,2864,0.0,0.0,50.0,41.0,45.5
495,2018-12-17,1291.425570,651.5,897304,1168919,0,1077,120,2808,0.0,0.0,48.0,38.0,43.0
496,2018-12-18,1743.626011,627.5,909101,1169714,0,1118,125,2968,0.0,0.0,40.0,29.0,34.5
497,2018-12-19,1842.445163,665.5,1070542,1284058,0,1169,127,3246,0.0,0.0,43.0,28.0,35.5
498,2018-12-20,1786.379916,714.0,990373,1167756,0,1182,129,3077,0.0,0.0,54.0,35.0,44.5
499,2018-12-21,1694.999243,675.5,817394,1329074,0,1042,119,2642,1.0,0.0,60.0,52.0,56.0
500,2018-12-24,907.955507,475.0,666251,1195274,0,713,105,1843,0.0,0.0,44.0,37.0,40.5
501,2018-12-26,943.476654,364.5,626731,1269673,0,781,99,2056,0.0,0.0,44.0,33.0,38.5
502,2018-12-27,1377.369615,569.0,797937,1190259,0,984,111,2600,0.0,0.0,46.0,39.0,42.5
503,2018-12-28,1420.501332,621.5,699880,1272483,0,887,109,2252,0.0,0.0,58.0,44.0,51.0
504,2018-12-31,1306.296117,524.5,586615,1329576,0,700,99,1648,NaN,NaN,NaN,NaN,NaN

In [ ]:
#df2.to_csv(path + "Qmatic Analysis.csv", index=False)

### ADD PREVIOUS VOLUME OF TRANSACTIONS AS VARIABLE

In [161]:
df2 = df2.sort_values(by = 'Date', ascending=True).reset_index(drop=True)

df2["Trans1DayAgo"] = 0.0
for i in range(1, len(df2)):
    df2["Trans1DayAgo"][i] = df2["Trans"][i-1]
    
#SET INDEX = 0 Trans1DayAgo to current day trans
df2["Trans1DayAgo"][0] = df2["Trans"][0]

In [162]:
df2

,Date,WAITING_TIME_mean,WAITING_TIME_median,SERVING_TIME,IDLE_TIME,SeasonFall,#CUSTOMERS,StaffCount,Trans,PRCP,SNOW,TMAX,TMIN,TAVE,Trans1DayAgo
0,2016-10-03,1402.766485,594.0,1085333,1797083,1,977,126,2745,0.0,0.0,72.0,60.0,66.0,2745.0
1,2016-10-04,1608.710671,666.0,3016194,4214952,1,929,119,2371,0.0,0.0,69.0,60.0,64.5,2745.0
2,2016-10-05,1363.989637,709.0,1466052,3841504,1,830,124,2123,0.0,0.0,67.0,53.0,60.0,2371.0
3,2016-10-06,1548.287252,793.0,903961,1629441,1,1117,128,2973,0.0,0.0,73.0,55.0,64.0,2123.0
4,2016-10-07,1362.754694,612.0,1294825,1710081,1,1158,125,3355,0.0,0.0,75.0,57.0,66.0,2973.0
5,2016-10-11,1698.428266,835.0,1569910,2642844,1,1091,134,2802,0.0,0.0,63.0,46.0,54.5,3355.0
6,2016-10-12,1159.869386,535.0,864970,1780717,1,973,123,2427,0.0,0.0,66.0,53.0,59.5,2802.0
7,2016-10-13,1524.265592,747.0,1126039,1929345,1,1205,137,3351,0.0,0.0,67.0,53.0,60.0,2427.0
8,2016-10-14,1641.643924,713.0,1514061,3891612,1,1181,135,3415,0.0,0.0,62.0,47.0,54.5,3351.0
9,2016-10-17,1449.208651,581.0,1060196,1772317,1,1070,121,2751,0.0,0.0,81.0,63.0,72.0,3415.0
10,2016-10-18,1347.635408,641.0,1143652,1720066,1,1214,143,3423,0.0,0.0,81.0,67.0,74.0,2751.0
11,2016-10-19,1516.164955,556.5,1268273,2051380,1,1163,128,3310,0.0,0.0,85.0,65.0,75.0,3423.0
12,2016-10-20,1293.847840,717.5,1294260,3143692,1,1138,131,3194,0.0,0.0,70.0,62.0,66.0,3310.0
13,2016-10-21,1714.826632,837.0,1410275,2650619,1,1106,132,3034,1.0,0.0,69.0,57.0,63.0,3194.0
14,2016-10-24,1293.852921,575.0,1077490,1672260,1,1076,122,2978,0.0,0.0,62.0,47.0,54.5,3034.0
15,2016-10-25,1341.936937,577.5,1209116,1906537,1,1181,137,3330,0.0,0.0,52.0,43.0,47.5,2978.0
16,2016-10-26,1302.165340,494.0,1179670,2041439,1,1173,139,3266,0.0,0.0,51.0,38.0,44.5,3330.0
17,2016-10-27,1530.535438,613.0,1176138,2138475,1,1202,135,3485,1.0,0.0,55.0,40.0,47.5,3266.0
18,2016-10-28,1376.379720,643.0,1135124,2004484,1,1182,131,3284,0.0,0.0,51.0,42.0,46.5,3485.0
19,2016-10-31,1031.448522,439.0,1022786,2139494,1,1057,133,2807,0.0,0.0,54.0,44.0,49.0,3284.0
20,2016-11-01,1227.227594,580.0,1154476,1797169,1,1195,137,3392,0.0,0.0,58.0,40.0,49.0,2807.0
21,2016-11-02,1289.398322,541.0,1187065,1894628,1,1217,136,3457,0.0,0.0,70.0,54.0,62.0,3392.0
22,2016-11-03,1678.797577,545.0,1133340,1751557,1,1201,132,3384,0.0,0.0,72.0,57.0,64.5,3457.0
23,2016-11-04,1696.713376,661.5,1160054,1951990,1,1226,130,3454,0.0,0.0,61.0,47.0,54.0,3384.0
24,2016-11-07,999.277328,486.0,1189990,2082959,1,1214,127,3458,0.0,0.0,53.0,41.0,47.0,3454.0
25,2016-11-09,2052.120125,938.5,1350571,2048696,1,1377,144,4154,1.0,0.0,59.0,49.0,54.0,3458.0
26,2016-11-10,1695.765852,903.0,1372383,1926745,1,1364,135,4053,0.0,0.0,56.0,40.0,48.0,4154.0
27,2016-11-14,1564.238876,813.0,1254929,1894650,1,1330,138,4023,0.0,0.0,62.0,46.0,54.0,4053.0
28,2016-11-15,1349.379675,787.5,1239517,2057745,1,1204,134,3690,1.0,0.0,56.0,47.0,51.5,4023.0
29,2016-11-16,1687.357576,713.0,1335674,1921003,1,1340,136,3795,0.0,0.0,61.0,45.0,53.0,3690.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2018-11-16,1104.730044,611.5,860433,1256972,1,1044,124,2756,1.0,0.0,45.0,34.0,39.5,3389.0
476,2018-11-19,1375.559929,710.0,1026088,1332609,1,1255,137,3379,0.0,0.0,50.0,41.0,45.5,2756.0
477,2018-11-20,1762.778431,827.0,1113004,1293803,1,1242,131,3403,0.0,0.0,47.0,39.0,43.0,3379.0
478,2018-11-21,1609.501129,862.0,1001231,1183912,1,1150,129,3099,0.0,0.0,44.0,27.0,35.5,3403.0
479,2018-11-23,842.791607,437.0,516511,1156345,1,558,94,1406,0.0,0.0,32.0,15.0,23.5,3099.0
480,2018-11-26,1051.694251,556.0,758742,1364360,1,1024,128,2731,1.0,0.0,53.0,45.0,49.0,1406.0
481,2018-11-27,1420.867848,684.0,970324,1184020,1,1159,125,3216,1.0,0.0,45.0,37.0,41.0,2731.0
482,2018-11-28,1234.641577,747.0,1024227,1277462,1,1212,133,3348,0.0,0.0,42.0,36.0,39.0,3216.0
483,2018-11-29,1127.441632,651.0,992657,1298248,1,1236,133,3358,0.0,0.0,46.0,38.0,42.0,3348.0
484,2018-11-30,1216.827714,645.5,931232,1115149,1,1100,126,2966,1.0,0.0,43.0,38.0,40.5,3358.0
485,2018-12-03,1434.221248,725.0,984143,1103347,0,1176,125,3078,0.0,0.0,55.0,46.0,50.5,2966.0
486,2018-12-04,1775.119740,847.5,1054844,1276342,0,1223,130,3232,0.0,0.0,46.0,31.0,38.5,3078.0
487,2018-12-05,1607.037512,855.0,954348,1284185,0,1199,126,3119,0.0,0.0,37.0,28.0,32.5,3232.0
488,2018-12-06,1556.371753,579.0,943434,1282307,0,1150,128,3080,0.0,0.0,40.0,30.0,35.0,3119.0
489,2018-12-07,1331.167974,602.0,960872,1129155,0,1154,129,3060,0.0,0.0,40.0,29.0,34.5,3080.0
490,2018-12-10,1264.566005,617.0,937928,1338739,0,1102,127,2871,0.0,0.0,41.0,30.0,35.5,3060.0
491,2018-12-11,1795.111660,756.0,937333,1186407,0,1163,127,3036,0.0,0.0,43.0,31.0,37.0,2871.0
492,2018-12-12,1551.491558,785.0,984158,1322685,0,1155,136,3139,0.0,0.0,42.0,34.0,38.0,3036.0
493,2018-12-13,2026.362245,678.0,1011451,1245801,0,1157,120,3136,0.0,0.0,42.0,35.0,38.5,3139.0
494,2018-12-14,1383.718226,642.0,861987,1203155,0,1098,124,2864,0.0,0.0,50.0,41.0,45.5,3136.0
495,2018-12-17,1291.425570,651.5,897304,1168919,0,1077,120,2808,0.0,0.0,48.0,38.0,43.0,2864.0
496,2018-12-18,1743.626011,627.5,909101,1169714,0,1118,125,2968,0.0,0.0,40.0,29.0,34.5,2808.0
497,2018-12-19,1842.445163,665.5,1070542,1284058,0,1169,127,3246,0.0,0.0,43.0,28.0,35.5,2968.0
498,2018-12-20,1786.379916,714.0,990373,1167756,0,1182,129,3077,0.0,0.0,54.0,35.0,44.5,3246.0
499,2018-12-21,1694.999243,675.5,817394,1329074,0,1042,119,2642,1.0,0.0,60.0,52.0,56.0,3077.0
500,2018-12-24,907.955507,475.0,666251,1195274,0,713,105,1843,0.0,0.0,44.0,37.0,40.5,2642.0
501,2018-12-26,943.476654,364.5,626731,1269673,0,781,99,2056,0.0,0.0,44.0,33.0,38.5,1843.0
502,2018-12-27,1377.369615,569.0,797937,1190259,0,984,111,2600,0.0,0.0,46.0,39.0,42.5,2056.0
503,2018-12-28,1420.501332,621.5,699880,1272483,0,887,109,2252,0.0,0.0,58.0,44.0,51.0,2600.0
504,2018-12-31,1306.296117,524.5,586615,1329576,0,700,99,1648,NaN,NaN,NaN,NaN,NaN,2252.0

### CREATE OUTCOME VARIABLE

In [163]:
df2["Target"] = 0
count=1
for i in range(0, len(df2)):
    if df2.WAITING_TIME_mean[i] >= 1500:
        df2["Target"][i] = 1
        count+=1
        
print "target number", count
print "target number percent", round( float(count)/len(df2), 3)

target number 101
target number percent 0.2

In [164]:
df2

,Date,WAITING_TIME_mean,WAITING_TIME_median,SERVING_TIME,IDLE_TIME,SeasonFall,#CUSTOMERS,StaffCount,Trans,PRCP,SNOW,TMAX,TMIN,TAVE,Trans1DayAgo,Target
0,2016-10-03,1402.766485,594.0,1085333,1797083,1,977,126,2745,0.0,0.0,72.0,60.0,66.0,2745.0,0
1,2016-10-04,1608.710671,666.0,3016194,4214952,1,929,119,2371,0.0,0.0,69.0,60.0,64.5,2745.0,1
2,2016-10-05,1363.989637,709.0,1466052,3841504,1,830,124,2123,0.0,0.0,67.0,53.0,60.0,2371.0,0
3,2016-10-06,1548.287252,793.0,903961,1629441,1,1117,128,2973,0.0,0.0,73.0,55.0,64.0,2123.0,1
4,2016-10-07,1362.754694,612.0,1294825,1710081,1,1158,125,3355,0.0,0.0,75.0,57.0,66.0,2973.0,0
5,2016-10-11,1698.428266,835.0,1569910,2642844,1,1091,134,2802,0.0,0.0,63.0,46.0,54.5,3355.0,1
6,2016-10-12,1159.869386,535.0,864970,1780717,1,973,123,2427,0.0,0.0,66.0,53.0,59.5,2802.0,0
7,2016-10-13,1524.265592,747.0,1126039,1929345,1,1205,137,3351,0.0,0.0,67.0,53.0,60.0,2427.0,1
8,2016-10-14,1641.643924,713.0,1514061,3891612,1,1181,135,3415,0.0,0.0,62.0,47.0,54.5,3351.0,1
9,2016-10-17,1449.208651,581.0,1060196,1772317,1,1070,121,2751,0.0,0.0,81.0,63.0,72.0,3415.0,0
10,2016-10-18,1347.635408,641.0,1143652,1720066,1,1214,143,3423,0.0,0.0,81.0,67.0,74.0,2751.0,0
11,2016-10-19,1516.164955,556.5,1268273,2051380,1,1163,128,3310,0.0,0.0,85.0,65.0,75.0,3423.0,1
12,2016-10-20,1293.847840,717.5,1294260,3143692,1,1138,131,3194,0.0,0.0,70.0,62.0,66.0,3310.0,0
13,2016-10-21,1714.826632,837.0,1410275,2650619,1,1106,132,3034,1.0,0.0,69.0,57.0,63.0,3194.0,1
14,2016-10-24,1293.852921,575.0,1077490,1672260,1,1076,122,2978,0.0,0.0,62.0,47.0,54.5,3034.0,0
15,2016-10-25,1341.936937,577.5,1209116,1906537,1,1181,137,3330,0.0,0.0,52.0,43.0,47.5,2978.0,0
16,2016-10-26,1302.165340,494.0,1179670,2041439,1,1173,139,3266,0.0,0.0,51.0,38.0,44.5,3330.0,0
17,2016-10-27,1530.535438,613.0,1176138,2138475,1,1202,135,3485,1.0,0.0,55.0,40.0,47.5,3266.0,1
18,2016-10-28,1376.379720,643.0,1135124,2004484,1,1182,131,3284,0.0,0.0,51.0,42.0,46.5,3485.0,0
19,2016-10-31,1031.448522,439.0,1022786,2139494,1,1057,133,2807,0.0,0.0,54.0,44.0,49.0,3284.0,0
20,2016-11-01,1227.227594,580.0,1154476,1797169,1,1195,137,3392,0.0,0.0,58.0,40.0,49.0,2807.0,0
21,2016-11-02,1289.398322,541.0,1187065,1894628,1,1217,136,3457,0.0,0.0,70.0,54.0,62.0,3392.0,0
22,2016-11-03,1678.797577,545.0,1133340,1751557,1,1201,132,3384,0.0,0.0,72.0,57.0,64.5,3457.0,1
23,2016-11-04,1696.713376,661.5,1160054,1951990,1,1226,130,3454,0.0,0.0,61.0,47.0,54.0,3384.0,1
24,2016-11-07,999.277328,486.0,1189990,2082959,1,1214,127,3458,0.0,0.0,53.0,41.0,47.0,3454.0,0
25,2016-11-09,2052.120125,938.5,1350571,2048696,1,1377,144,4154,1.0,0.0,59.0,49.0,54.0,3458.0,1
26,2016-11-10,1695.765852,903.0,1372383,1926745,1,1364,135,4053,0.0,0.0,56.0,40.0,48.0,4154.0,1
27,2016-11-14,1564.238876,813.0,1254929,1894650,1,1330,138,4023,0.0,0.0,62.0,46.0,54.0,4053.0,1
28,2016-11-15,1349.379675,787.5,1239517,2057745,1,1204,134,3690,1.0,0.0,56.0,47.0,51.5,4023.0,0
29,2016-11-16,1687.357576,713.0,1335674,1921003,1,1340,136,3795,0.0,0.0,61.0,45.0,53.0,3690.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2018-11-16,1104.730044,611.5,860433,1256972,1,1044,124,2756,1.0,0.0,45.0,34.0,39.5,3389.0,0
476,2018-11-19,1375.559929,710.0,1026088,1332609,1,1255,137,3379,0.0,0.0,50.0,41.0,45.5,2756.0,0
477,2018-11-20,1762.778431,827.0,1113004,1293803,1,1242,131,3403,0.0,0.0,47.0,39.0,43.0,3379.0,1
478,2018-11-21,1609.501129,862.0,1001231,1183912,1,1150,129,3099,0.0,0.0,44.0,27.0,35.5,3403.0,1
479,2018-11-23,842.791607,437.0,516511,1156345,1,558,94,1406,0.0,0.0,32.0,15.0,23.5,3099.0,0
480,2018-11-26,1051.694251,556.0,758742,1364360,1,1024,128,2731,1.0,0.0,53.0,45.0,49.0,1406.0,0
481,2018-11-27,1420.867848,684.0,970324,1184020,1,1159,125,3216,1.0,0.0,45.0,37.0,41.0,2731.0,0
482,2018-11-28,1234.641577,747.0,1024227,1277462,1,1212,133,3348,0.0,0.0,42.0,36.0,39.0,3216.0,0
483,2018-11-29,1127.441632,651.0,992657,1298248,1,1236,133,3358,0.0,0.0,46.0,38.0,42.0,3348.0,0
484,2018-11-30,1216.827714,645.5,931232,1115149,1,1100,126,2966,1.0,0.0,43.0,38.0,40.5,3358.0,0
485,2018-12-03,1434.221248,725.0,984143,1103347,0,1176,125,3078,0.0,0.0,55.0,46.0,50.5,2966.0,0
486,2018-12-04,1775.119740,847.5,1054844,1276342,0,1223,130,3232,0.0,0.0,46.0,31.0,38.5,3078.0,1
487,2018-12-05,1607.037512,855.0,954348,1284185,0,1199,126,3119,0.0,0.0,37.0,28.0,32.5,3232.0,1
488,2018-12-06,1556.371753,579.0,943434,1282307,0,1150,128,3080,0.0,0.0,40.0,30.0,35.0,3119.0,1
489,2018-12-07,1331.167974,602.0,960872,1129155,0,1154,129,3060,0.0,0.0,40.0,29.0,34.5,3080.0,0
490,2018-12-10,1264.566005,617.0,937928,1338739,0,1102,127,2871,0.0,0.0,41.0,30.0,35.5,3060.0,0
491,2018-12-11,1795.111660,756.0,937333,1186407,0,1163,127,3036,0.0,0.0,43.0,31.0,37.0,2871.0,1
492,2018-12-12,1551.491558,785.0,984158,1322685,0,1155,136,3139,0.0,0.0,42.0,34.0,38.0,3036.0,1
493,2018-12-13,2026.362245,678.0,1011451,1245801,0,1157,120,3136,0.0,0.0,42.0,35.0,38.5,3139.0,1
494,2018-12-14,1383.718226,642.0,861987,1203155,0,1098,124,2864,0.0,0.0,50.0,41.0,45.5,3136.0,0
495,2018-12-17,1291.425570,651.5,897304,1168919,0,1077,120,2808,0.0,0.0,48.0,38.0,43.0,2864.0,0
496,2018-12-18,1743.626011,627.5,909101,1169714,0,1118,125,2968,0.0,0.0,40.0,29.0,34.5,2808.0,1
497,2018-12-19,1842.445163,665.5,1070542,1284058,0,1169,127,3246,0.0,0.0,43.0,28.0,35.5,2968.0,1
498,2018-12-20,1786.379916,714.0,990373,1167756,0,1182,129,3077,0.0,0.0,54.0,35.0,44.5,3246.0,1
499,2018-12-21,1694.999243,675.5,817394,1329074,0,1042,119,2642,1.0,0.0,60.0,52.0,56.0,3077.0,1
500,2018-12-24,907.955507,475.0,666251,1195274,0,713,105,1843,0.0,0.0,44.0,37.0,40.5,2642.0,0
501,2018-12-26,943.476654,364.5,626731,1269673,0,781,99,2056,0.0,0.0,44.0,33.0,38.5,1843.0,0
502,2018-12-27,1377.369615,569.0,797937,1190259,0,984,111,2600,0.0,0.0,46.0,39.0,42.5,2056.0,0
503,2018-12-28,1420.501332,621.5,699880,1272483,0,887,109,2252,0.0,0.0,58.0,44.0,51.0,2600.0,0
504,2018-12-31,1306.296117,524.5,586615,1329576,0,700,99,1648,NaN,NaN,NaN,NaN,NaN,2252.0,0

In [91]:
df2.to_csv(path + "Qmatic Analysis NEW.csv", index=False)

In [ ]:
#df2.to_csv(path + "test.csv", index=False)

### CREATE SERVICE CATEGORY AND DELIVERED SERVICE DUMMIES

SERVICE CATEGORIES

In [165]:
#FIRST DETERMINE MOST CURRENT SERVICE CATEGORY
df_sc = df.copy()

df_sc = df_sc.rename(columns={'Service Category': 'ServiceCategory'})

types = df_sc[["Date", "WAITING_TIME", "ServiceCategory"]]

from datetime import date
from dateutil.relativedelta import relativedelta
from dateutil import parser

import datetime
import time
ts = time.time()
st = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')
print st

#get dates from one month ago
types['Date'] = pd.to_datetime(types['Date'])
#dfu = dfu.sort_values(by = 'D_DATE1', ascending=True).reset_index(drop=True)
ts = time.time()
date = datetime.datetime.fromtimestamp(ts).strftime('%m-%d-%Y')
date = parser.parse(date)
date =  date.date()
one_month_ago = date.today() + relativedelta(months=-1)
print "One Month Ago:", one_month_ago
mask = (types['Date'] >= one_month_ago)
types = types.loc[mask]
types = types.reset_index(drop=True)


types = sorted( list(set( types["ServiceCategory"].tolist() ) ) )
print len(types)


delService_dummies = pd.get_dummies(df_sc.ServiceCategory, prefix='SC')
df_sc = pd.concat([df_sc, delService_dummies], axis=1)

df_sc = df_sc.drop('WAITING_TIME', 1)
df_sc = df_sc.drop('ServiceCategory', 1)

df_sc = df_sc.groupby(['Date']).sum()
df_sc = df_sc.add_suffix('').reset_index()

2019-01-16 09:40:01
One Month Ago: 2018-12-16
98

MERGE

In [166]:
for i in range(0, len(types)):
    types[i] = "SC_" + types[i]
    
types =  ['Date']  + types
df4 = df_sc[types]

df2 = pd.merge(df2, df4, how='left', on=['Date'])

In [167]:
#df2.to_csv(path + "test.csv")

len(df2.columns)

114

DELIVIERED SERVICE

In [168]:
import pandas as pd
import numpy as np
import glob 

#path = "C:\\Users\\dmehri\\Documents\\DATA\\Qmatic Predictive Modelling\\"

#df = pd.read_csv(path + "QMATIC.csv")

print "Reading data..."
i=0
all_data = pd.DataFrame()
for f in glob.glob("C:\Users\dmehri\Documents\DATA\Qmatic Predictive Modelling\data\Delivered Service\*.csv"):
    i+=1
    print i
    dfAppend = pd.read_csv(f)
    #get rid of Westchester
    all_data = all_data.append(dfAppend,ignore_index=True)


ds = all_data.copy()
print "creating date ..."

ds["MONTH"] = ds["MONTH"].astype(str)
ds["DAY"] = ds["DAY"].astype(str)
ds["YEAR"] = ds["YEAR"].astype(str)
ds["Date"] = ds["MONTH"] + "-" + ds["DAY"] + "-" + ds["YEAR"]

print "creating datetime..."

ds = ds[["Date", "VISIT_KEY", "NAME.1"]]
ds['Date'] = pd.to_datetime(ds['Date'])
ds["Date"] = ds["Date"].apply(lambda x: x.date())
ds = ds.rename(columns={'NAME.1': 'DELIVERED_SERVICE'})

Reading data...
1
2
3
4
5
creating date ...
creating datetime...

In [169]:
ds.head(1)

         Date  VISIT_KEY DELIVERED_SERVICE
0  2016-05-02     207181      RR - Records

In [170]:
#FIRST DETERMINE MOST CURRENT DELIVERED SERVICE CATEGORIES
#df3 = df.copy()

ds2 = ds.copy()

typesds = ds2[["Date", "DELIVERED_SERVICE"]]

from datetime import date
from dateutil.relativedelta import relativedelta
from dateutil import parser

import datetime
import time
ts = time.time()
st = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')
print st

#get dates from one month ago
typesds['Date'] = pd.to_datetime(typesds['Date'])
#dfu = dfu.sort_values(by = 'D_DATE1', ascending=True).reset_index(drop=True)
ts = time.time()
date = datetime.datetime.fromtimestamp(ts).strftime('%m-%d-%Y')
date = parser.parse(date)
date =  date.date()
one_month_ago = date.today() + relativedelta(months=-1)
print "One Month Ago:", one_month_ago
mask = (typesds['Date'] >= one_month_ago)
typesds = typesds.loc[mask]
typesds = typesds.reset_index(drop=True)

typesds = sorted( list(set( typesds["DELIVERED_SERVICE"].tolist() ) ) )
print len(typesds)


delService_dummies = pd.get_dummies(ds2.DELIVERED_SERVICE, prefix='DS')
ds2 = pd.concat([ds2, delService_dummies], axis=1)

ds2 = ds2.drop('VISIT_KEY', 1)
ds2 = ds2.drop('DELIVERED_SERVICE', 1)

ds2 = ds2.groupby(['Date']).sum()
ds2 = ds2.add_suffix('').reset_index()

2019-01-16 09:51:28
One Month Ago: 2018-12-16
135

MERGE

In [171]:
for i in range(0, len(typesds)):
    typesds[i] = "DS_" + typesds[i]
    
typesds =  ['Date']  + typesds
ds3 = ds2[typesds]

df2 = pd.merge(df2, ds3, how='left', on=['Date'])

In [ ]:
len(df2.columns)

In [ ]:

#df3['Target'] = np.where(df3['WAITING_TIME'] >= 1800, '1', '0')
#df["WAITING_TIME"] = df["WAITING_TIME"].astype(float)
#df3['Target'] = df.WAITING_TIME.map( lambda x: 1 if x >= 1800 else 0)

In [ ]:
#df4 = df3[["Date",  "DS_Permit - Initial", "DS_Certificate of Correction (in-person)", "DS_AP - DEAR - Correction"]]

#Just include 3 top delivered service for target=1, did not meet delivered service

#merge

In [ ]:
df2.dtypes

### SPEARMAN CORRELATION ANALYSIS

In [97]:
import scipy
from scipy import stats

typesSpearHigh = []

def SpearCorr(df, wait_time, types):
    for i in range(0, len(types)):
        thetype = df[types[i]]
        #print types[i]
        #print wait_time
        #print thetype
        spcorr = scipy.stats.spearmanr(wait_time, thetype)
        
        if (spcorr[0] >= 0.35 or spcorr[0] <= -0.35):
            print types[i]
            typesSpearHigh.append(types[i])
            print spcorr
            print 
        
    
#types2 = types +  ["StaffCount","Trans", "PRCP", "SNOW", "TMAX", "TMIN", "TAVE", "Trans1DayAgo"]

#types.remove("Date")  
wait_time = df2["WAITING_TIME_mean"]
types_all = types + typesds
SpearCorr(df2,wait_time, types_all )




"""
df_temp = df2[df2["DS_Permit - Initial"] != 0]
wait_time = df_temp["WAITING_TIME_mean"]
permit_intitial = df_temp["DS_Permit - Initial"]

#scipy.stats.spearmanr([1,2,3,4,5], [5,6,7,8,7])

print scipy.stats.spearmanr(wait_time, permit_intitial)

#DS_AP - DEAR - Correction
wait_time = df2["WAITING_TIME_mean"]
ap_dear = df2["DS_AP - DEAR - Correction"]

print scipy.stats.spearmanr(wait_time, ap_dear)

#DS_Certificate of Correction (in-person)
df_temp = df2[df2["DS_Certificate of Correction (in-person)"] != 0]
wait_time = df_temp["WAITING_TIME_mean"]
permit_intitial = df_temp["DS_Certificate of Correction (in-person)"]
print scipy.stats.spearmanr(wait_time, permit_intitial)

"""

C:\ProgramData\Anaconda2\lib\site-packages\scipy\stats\stats.py:250: RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
  "values. nan values will be ignored.", RuntimeWarning)

SC_Fast App
SpearmanrResult(correlation=0.37524433714626365, pvalue=2.4841594063880403e-18)

DS_AP - ProCert Filing
SpearmanrResult(correlation=0.37367161801052506, pvalue=3.5203427042230549e-18)

'\ndf_temp = df2[df2["DS_Permit - Initial"] != 0]\nwait_time = df_temp["WAITING_TIME_mean"]\npermit_intitial = df_temp["DS_Permit - Initial"]\n\n#scipy.stats.spearmanr([1,2,3,4,5], [5,6,7,8,7])\n\nprint scipy.stats.spearmanr(wait_time, permit_intitial)\n\n#DS_AP - DEAR - Correction\nwait_time = df2["WAITING_TIME_mean"]\nap_dear = df2["DS_AP - DEAR - Correction"]\n\nprint scipy.stats.spearmanr(wait_time, ap_dear)\n\n#DS_Certificate of Correction (in-person)\ndf_temp = df2[df2["DS_Certificate of Correction (in-person)"] != 0]\nwait_time = df_temp["WAITING_TIME_mean"]\npermit_intitial = df_temp["DS_Certificate of Correction (in-person)"]\nprint scipy.stats.spearmanr(wait_time, permit_intitial)\n\n'

In [98]:
typesSpearHigh

['SC_Fast App', 'DS_AP - ProCert Filing']

In [172]:
df2.dtypes

Date                                                      object
WAITING_TIME_mean                                        float64
WAITING_TIME_median                                      float64
SERVING_TIME                                               int32
IDLE_TIME                                                  int64
SeasonFall                                                 int64
#CUSTOMERS                                                 int64
StaffCount                                                 int64
Trans                                                      int64
PRCP                                                     float64
SNOW                                                     float64
TMAX                                                     float64
TMIN                                                     float64
TAVE                                                     float64
Trans1DayAgo                                             float64
Target                                                     int64
SC_1st-Admin Sign-Off/Withdrawal Appt                    float64
SC_1st-Boiler                                            float64
SC_1st-CS-Applying for New License/Registration          float64
SC_1st-CS-Approved for New License/Registration          float64
SC_1st-CSM-Applying for New License/Registration -CSR    float64
SC_1st-CSM-Approved for New License/Registration         float64
SC_1st-Central Cashier                                   float64
SC_1st-Central Filing & Billing                          float64
SC_1st-Central Inspections Cashier                       float64
SC_1st-E-Applying for New License/Registration           float64
SC_1st-E-Approved for New License/Registration           float64
SC_1st-E-Existing Licensee Changes                       float64
SC_1st-E-License Renewals                                float64
SC_1st-E-Lost License                                    float64
                                                          ...
DS_Plan Exam Meeting                                     float64
DS_Plan Pick up                                          float64
DS_RR - Blk./Lot Entire folder or microfilm              float64
DS_RR - Copy of Plans / Documents                        float64
DS_RR - Docket Books                                     float64
DS_RR - EUP Cards                                        float64
DS_RR - Index Reels                                      float64
DS_RR - Job Folders                                      float64
DS_RR - Microfiche / Microfilm                           float64
DS_RR - Offsite Request                                  float64
DS_RR - Records                                          float64
DS_RR - Research of Certificate of Occupancy             float64
DS_Reinstatement Approval                                float64
DS_Reinstatement/Renewal/PPNs                            float64
DS_Research                                              float64
DS_SWO Rescission                                        float64
DS_Same Day Dropoff                                      float64
DS_Same Day Processing                                   float64
DS_Scaffold/C-Hook Inquiry                               float64
DS_Scaffold/C-Hook Payment                               float64
DS_Seal & Plate                                          float64
DS_Seal and Plate                                        float64
DS_Sheds                                                 float64
DS_Sign-Off Questions/Issues                             float64
DS_Ticket does not match ID                              float64
DS_Unprepared                                            float64
DS_Violation-Inquiry                                     float64
DS_Violation-Payment                                     float64
DS_Waivers                                               float64
DS_Withdrawls/Admin Sign Off                             float64
dtype: object

### CREATE FINAL DATASET

In [174]:
#LOW COUNT FOR AP AFTER HOURS VARIANCE
df3 = df2.copy()

#typesSpearHigh.remove("DS_AP - After Hours Variance")

print typesSpearHigh

PrevVarList = ["Date",  "Target","WAITING_TIME_mean", "StaffCount","Trans", "PRCP", "SNOW", "TMAX","SeasonFall",
              "TMIN", "TAVE", "Trans1DayAgo", "#CUSTOMERS", "SERVING_TIME", "IDLE_TIME"]

finalVarList = PrevVarList +  typesSpearHigh

df3 = df3[finalVarList]

['SC_Fast App', 'DS_AP - ProCert Filing']

In [175]:
df3

,Date,Target,WAITING_TIME_mean,StaffCount,Trans,PRCP,SNOW,TMAX,SeasonFall,TMIN,TAVE,Trans1DayAgo,#CUSTOMERS,SERVING_TIME,IDLE_TIME,SC_Fast App,DS_AP - ProCert Filing
0,2016-10-03,0,1402.766485,126,2745,0.0,0.0,72.0,1,60.0,66.0,2745.0,977,1085333,1797083,146.0,57.0
1,2016-10-04,1,1608.710671,119,2371,0.0,0.0,69.0,1,60.0,64.5,2745.0,929,3016194,4214952,108.0,34.0
2,2016-10-05,0,1363.989637,124,2123,0.0,0.0,67.0,1,53.0,60.0,2371.0,830,1466052,3841504,107.0,55.0
3,2016-10-06,1,1548.287252,128,2973,0.0,0.0,73.0,1,55.0,64.0,2123.0,1117,903961,1629441,122.0,55.0
4,2016-10-07,0,1362.754694,125,3355,0.0,0.0,75.0,1,57.0,66.0,2973.0,1158,1294825,1710081,172.0,73.0
5,2016-10-11,1,1698.428266,134,2802,0.0,0.0,63.0,1,46.0,54.5,3355.0,1091,1569910,2642844,172.0,60.0
6,2016-10-12,0,1159.869386,123,2427,0.0,0.0,66.0,1,53.0,59.5,2802.0,973,864970,1780717,107.0,50.0
7,2016-10-13,1,1524.265592,137,3351,0.0,0.0,67.0,1,53.0,60.0,2427.0,1205,1126039,1929345,170.0,82.0
8,2016-10-14,1,1641.643924,135,3415,0.0,0.0,62.0,1,47.0,54.5,3351.0,1181,1514061,3891612,206.0,72.0
9,2016-10-17,0,1449.208651,121,2751,0.0,0.0,81.0,1,63.0,72.0,3415.0,1070,1060196,1772317,112.0,61.0
10,2016-10-18,0,1347.635408,143,3423,0.0,0.0,81.0,1,67.0,74.0,2751.0,1214,1143652,1720066,159.0,74.0
11,2016-10-19,1,1516.164955,128,3310,0.0,0.0,85.0,1,65.0,75.0,3423.0,1163,1268273,2051380,175.0,93.0
12,2016-10-20,0,1293.847840,131,3194,0.0,0.0,70.0,1,62.0,66.0,3310.0,1138,1294260,3143692,196.0,75.0
13,2016-10-21,1,1714.826632,132,3034,1.0,0.0,69.0,1,57.0,63.0,3194.0,1106,1410275,2650619,152.0,75.0
14,2016-10-24,0,1293.852921,122,2978,0.0,0.0,62.0,1,47.0,54.5,3034.0,1076,1077490,1672260,163.0,49.0
15,2016-10-25,0,1341.936937,137,3330,0.0,0.0,52.0,1,43.0,47.5,2978.0,1181,1209116,1906537,170.0,86.0
16,2016-10-26,0,1302.165340,139,3266,0.0,0.0,51.0,1,38.0,44.5,3330.0,1173,1179670,2041439,155.0,75.0
17,2016-10-27,1,1530.535438,135,3485,1.0,0.0,55.0,1,40.0,47.5,3266.0,1202,1176138,2138475,159.0,76.0
18,2016-10-28,0,1376.379720,131,3284,0.0,0.0,51.0,1,42.0,46.5,3485.0,1182,1135124,2004484,178.0,61.0
19,2016-10-31,0,1031.448522,133,2807,0.0,0.0,54.0,1,44.0,49.0,3284.0,1057,1022786,2139494,126.0,33.0
20,2016-11-01,0,1227.227594,137,3392,0.0,0.0,58.0,1,40.0,49.0,2807.0,1195,1154476,1797169,157.0,46.0
21,2016-11-02,0,1289.398322,136,3457,0.0,0.0,70.0,1,54.0,62.0,3392.0,1217,1187065,1894628,190.0,50.0
22,2016-11-03,1,1678.797577,132,3384,0.0,0.0,72.0,1,57.0,64.5,3457.0,1201,1133340,1751557,185.0,61.0
23,2016-11-04,1,1696.713376,130,3454,0.0,0.0,61.0,1,47.0,54.0,3384.0,1226,1160054,1951990,178.0,58.0
24,2016-11-07,0,999.277328,127,3458,0.0,0.0,53.0,1,41.0,47.0,3454.0,1214,1189990,2082959,193.0,67.0
25,2016-11-09,1,2052.120125,144,4154,1.0,0.0,59.0,1,49.0,54.0,3458.0,1377,1350571,2048696,271.0,59.0
26,2016-11-10,1,1695.765852,135,4053,0.0,0.0,56.0,1,40.0,48.0,4154.0,1364,1372383,1926745,239.0,77.0
27,2016-11-14,1,1564.238876,138,4023,0.0,0.0,62.0,1,46.0,54.0,4053.0,1330,1254929,1894650,229.0,71.0
28,2016-11-15,0,1349.379675,134,3690,1.0,0.0,56.0,1,47.0,51.5,4023.0,1204,1239517,2057745,200.0,47.0
29,2016-11-16,1,1687.357576,136,3795,0.0,0.0,61.0,1,45.0,53.0,3690.0,1340,1335674,1921003,182.0,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2018-11-16,0,1104.730044,124,2756,1.0,0.0,45.0,1,34.0,39.5,3389.0,1044,860433,1256972,179.0,28.0
476,2018-11-19,0,1375.559929,137,3379,0.0,0.0,50.0,1,41.0,45.5,2756.0,1255,1026088,1332609,174.0,26.0
477,2018-11-20,1,1762.778431,131,3403,0.0,0.0,47.0,1,39.0,43.0,3379.0,1242,1113004,1293803,174.0,24.0
478,2018-11-21,1,1609.501129,129,3099,0.0,0.0,44.0,1,27.0,35.5,3403.0,1150,1001231,1183912,193.0,34.0
479,2018-11-23,0,842.791607,94,1406,0.0,0.0,32.0,1,15.0,23.5,3099.0,558,516511,1156345,76.0,14.0
480,2018-11-26,0,1051.694251,128,2731,1.0,0.0,53.0,1,45.0,49.0,1406.0,1024,758742,1364360,126.0,4.0
481,2018-11-27,0,1420.867848,125,3216,1.0,0.0,45.0,1,37.0,41.0,2731.0,1159,970324,1184020,187.0,26.0
482,2018-11-28,0,1234.641577,133,3348,0.0,0.0,42.0,1,36.0,39.0,3216.0,1212,1024227,1277462,166.0,49.0
483,2018-11-29,0,1127.441632,133,3358,0.0,0.0,46.0,1,38.0,42.0,3348.0,1236,992657,1298248,178.0,43.0
484,2018-11-30,0,1216.827714,126,2966,1.0,0.0,43.0,1,38.0,40.5,3358.0,1100,931232,1115149,163.0,50.0
485,2018-12-03,0,1434.221248,125,3078,0.0,0.0,55.0,0,46.0,50.5,2966.0,1176,984143,1103347,184.0,51.0
486,2018-12-04,1,1775.119740,130,3232,0.0,0.0,46.0,0,31.0,38.5,3078.0,1223,1054844,1276342,187.0,27.0
487,2018-12-05,1,1607.037512,126,3119,0.0,0.0,37.0,0,28.0,32.5,3232.0,1199,954348,1284185,169.0,59.0
488,2018-12-06,1,1556.371753,128,3080,0.0,0.0,40.0,0,30.0,35.0,3119.0,1150,943434,1282307,172.0,53.0
489,2018-12-07,0,1331.167974,129,3060,0.0,0.0,40.0,0,29.0,34.5,3080.0,1154,960872,1129155,170.0,86.0
490,2018-12-10,0,1264.566005,127,2871,0.0,0.0,41.0,0,30.0,35.5,3060.0,1102,937928,1338739,171.0,61.0
491,2018-12-11,1,1795.111660,127,3036,0.0,0.0,43.0,0,31.0,37.0,2871.0,1163,937333,1186407,163.0,125.0
492,2018-12-12,1,1551.491558,136,3139,0.0,0.0,42.0,0,34.0,38.0,3036.0,1155,984158,1322685,188.0,85.0
493,2018-12-13,1,2026.362245,120,3136,0.0,0.0,42.0,0,35.0,38.5,3139.0,1157,1011451,1245801,193.0,55.0
494,2018-12-14,0,1383.718226,124,2864,0.0,0.0,50.0,0,41.0,45.5,3136.0,1098,861987,1203155,163.0,93.0
495,2018-12-17,0,1291.425570,120,2808,0.0,0.0,48.0,0,38.0,43.0,2864.0,1077,897304,1168919,172.0,74.0
496,2018-12-18,1,1743.626011,125,2968,0.0,0.0,40.0,0,29.0,34.5,2808.0,1118,909101,1169714,178.0,57.0
497,2018-12-19,1,1842.445163,127,3246,0.0,0.0,43.0,0,28.0,35.5,2968.0,1169,1070542,1284058,207.0,74.0
498,2018-12-20,1,1786.379916,129,3077,0.0,0.0,54.0,0,35.0,44.5,3246.0,1182,990373,1167756,196.0,69.0
499,2018-12-21,1,1694.999243,119,2642,1.0,0.0,60.0,0,52.0,56.0,3077.0,1042,817394,1329074,174.0,42.0
500,2018-12-24,0,907.955507,105,1843,0.0,0.0,44.0,0,37.0,40.5,2642.0,713,666251,1195274,108.0,26.0
501,2018-12-26,0,943.476654,99,2056,0.0,0.0,44.0,0,33.0,38.5,1843.0,781,626731,1269673,104.0,27.0
502,2018-12-27,0,1377.369615,111,2600,0.0,0.0,46.0,0,39.0,42.5,2056.0,984,797937,1190259,159.0,61.0
503,2018-12-28,0,1420.501332,109,2252,0.0,0.0,58.0,0,44.0,51.0,2600.0,887,699880,1272483,125.0,43.0
504,2018-12-31,0,1306.296117,99,1648,NaN,NaN,NaN,0,NaN,NaN,2252.0,700,586615,1329576,83.0,11.0

In [ ]:
df3.to_csv(path + "test.csv", index=False)

### QMATIC Model

Final Model

In [ ]:
df_final

In [186]:
df_final = df3.copy()
#df_final = df_final.drop('WAITING_TIME_mean', 1)
#df_final = df_final.drop('Date', 1)

model1 = ["Target", "TMAX", "TMIN","TAVE", "SNOW", "PRCP", "Trans", "Trans1DayAgo", "StaffCount", "#CUSTOMERS", "SeasonFall",
          "SERVING_TIME", "IDLE_TIME", "SC_Fast App",  'DS_AP - ProCert Filing']

#df_final = df_final[model1]


model2 = ["Target","SeasonFall","DS_AP - ProCert Filing","#CUSTOMERS", "SC_Fast App", "StaffCount", "IDLE_TIME", "TMIN" ]

#df_final = df_final[model2]


model3 = ["Target","SeasonFall","DS_AP - ProCert Filing","#CUSTOMERS", "SC_Fast App" ]

df_final = df_final[model3]


print "drop NaN", len(df_final)
df_final = df_final.dropna()
print "after drop", len(df_final)

drop NaN 505
after drop 505

In [213]:
df3.to_csv(path + "Qmatic Pred Final Model Data Target=20min.csv")

In [212]:
df3

,Date,Target,WAITING_TIME_mean,StaffCount,Trans,PRCP,SNOW,TMAX,SeasonFall,TMIN,TAVE,Trans1DayAgo,#CUSTOMERS,SERVING_TIME,IDLE_TIME,SC_Fast App,DS_AP - ProCert Filing
0,2016-10-03,0,1402.766485,126,2745,0.0,0.0,72.0,1,60.0,66.0,2745.0,977,1085333,1797083,146.0,57.0
1,2016-10-04,1,1608.710671,119,2371,0.0,0.0,69.0,1,60.0,64.5,2745.0,929,3016194,4214952,108.0,34.0
2,2016-10-05,0,1363.989637,124,2123,0.0,0.0,67.0,1,53.0,60.0,2371.0,830,1466052,3841504,107.0,55.0
3,2016-10-06,1,1548.287252,128,2973,0.0,0.0,73.0,1,55.0,64.0,2123.0,1117,903961,1629441,122.0,55.0
4,2016-10-07,0,1362.754694,125,3355,0.0,0.0,75.0,1,57.0,66.0,2973.0,1158,1294825,1710081,172.0,73.0
5,2016-10-11,1,1698.428266,134,2802,0.0,0.0,63.0,1,46.0,54.5,3355.0,1091,1569910,2642844,172.0,60.0
6,2016-10-12,0,1159.869386,123,2427,0.0,0.0,66.0,1,53.0,59.5,2802.0,973,864970,1780717,107.0,50.0
7,2016-10-13,1,1524.265592,137,3351,0.0,0.0,67.0,1,53.0,60.0,2427.0,1205,1126039,1929345,170.0,82.0
8,2016-10-14,1,1641.643924,135,3415,0.0,0.0,62.0,1,47.0,54.5,3351.0,1181,1514061,3891612,206.0,72.0
9,2016-10-17,0,1449.208651,121,2751,0.0,0.0,81.0,1,63.0,72.0,3415.0,1070,1060196,1772317,112.0,61.0
10,2016-10-18,0,1347.635408,143,3423,0.0,0.0,81.0,1,67.0,74.0,2751.0,1214,1143652,1720066,159.0,74.0
11,2016-10-19,1,1516.164955,128,3310,0.0,0.0,85.0,1,65.0,75.0,3423.0,1163,1268273,2051380,175.0,93.0
12,2016-10-20,0,1293.847840,131,3194,0.0,0.0,70.0,1,62.0,66.0,3310.0,1138,1294260,3143692,196.0,75.0
13,2016-10-21,1,1714.826632,132,3034,1.0,0.0,69.0,1,57.0,63.0,3194.0,1106,1410275,2650619,152.0,75.0
14,2016-10-24,0,1293.852921,122,2978,0.0,0.0,62.0,1,47.0,54.5,3034.0,1076,1077490,1672260,163.0,49.0
15,2016-10-25,0,1341.936937,137,3330,0.0,0.0,52.0,1,43.0,47.5,2978.0,1181,1209116,1906537,170.0,86.0
16,2016-10-26,0,1302.165340,139,3266,0.0,0.0,51.0,1,38.0,44.5,3330.0,1173,1179670,2041439,155.0,75.0
17,2016-10-27,1,1530.535438,135,3485,1.0,0.0,55.0,1,40.0,47.5,3266.0,1202,1176138,2138475,159.0,76.0
18,2016-10-28,0,1376.379720,131,3284,0.0,0.0,51.0,1,42.0,46.5,3485.0,1182,1135124,2004484,178.0,61.0
19,2016-10-31,0,1031.448522,133,2807,0.0,0.0,54.0,1,44.0,49.0,3284.0,1057,1022786,2139494,126.0,33.0
20,2016-11-01,0,1227.227594,137,3392,0.0,0.0,58.0,1,40.0,49.0,2807.0,1195,1154476,1797169,157.0,46.0
21,2016-11-02,0,1289.398322,136,3457,0.0,0.0,70.0,1,54.0,62.0,3392.0,1217,1187065,1894628,190.0,50.0
22,2016-11-03,1,1678.797577,132,3384,0.0,0.0,72.0,1,57.0,64.5,3457.0,1201,1133340,1751557,185.0,61.0
23,2016-11-04,1,1696.713376,130,3454,0.0,0.0,61.0,1,47.0,54.0,3384.0,1226,1160054,1951990,178.0,58.0
24,2016-11-07,0,999.277328,127,3458,0.0,0.0,53.0,1,41.0,47.0,3454.0,1214,1189990,2082959,193.0,67.0
25,2016-11-09,1,2052.120125,144,4154,1.0,0.0,59.0,1,49.0,54.0,3458.0,1377,1350571,2048696,271.0,59.0
26,2016-11-10,1,1695.765852,135,4053,0.0,0.0,56.0,1,40.0,48.0,4154.0,1364,1372383,1926745,239.0,77.0
27,2016-11-14,1,1564.238876,138,4023,0.0,0.0,62.0,1,46.0,54.0,4053.0,1330,1254929,1894650,229.0,71.0
28,2016-11-15,0,1349.379675,134,3690,1.0,0.0,56.0,1,47.0,51.5,4023.0,1204,1239517,2057745,200.0,47.0
29,2016-11-16,1,1687.357576,136,3795,0.0,0.0,61.0,1,45.0,53.0,3690.0,1340,1335674,1921003,182.0,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2018-11-16,0,1104.730044,124,2756,1.0,0.0,45.0,1,34.0,39.5,3389.0,1044,860433,1256972,179.0,28.0
476,2018-11-19,0,1375.559929,137,3379,0.0,0.0,50.0,1,41.0,45.5,2756.0,1255,1026088,1332609,174.0,26.0
477,2018-11-20,1,1762.778431,131,3403,0.0,0.0,47.0,1,39.0,43.0,3379.0,1242,1113004,1293803,174.0,24.0
478,2018-11-21,1,1609.501129,129,3099,0.0,0.0,44.0,1,27.0,35.5,3403.0,1150,1001231,1183912,193.0,34.0
479,2018-11-23,0,842.791607,94,1406,0.0,0.0,32.0,1,15.0,23.5,3099.0,558,516511,1156345,76.0,14.0
480,2018-11-26,0,1051.694251,128,2731,1.0,0.0,53.0,1,45.0,49.0,1406.0,1024,758742,1364360,126.0,4.0
481,2018-11-27,0,1420.867848,125,3216,1.0,0.0,45.0,1,37.0,41.0,2731.0,1159,970324,1184020,187.0,26.0
482,2018-11-28,0,1234.641577,133,3348,0.0,0.0,42.0,1,36.0,39.0,3216.0,1212,1024227,1277462,166.0,49.0
483,2018-11-29,0,1127.441632,133,3358,0.0,0.0,46.0,1,38.0,42.0,3348.0,1236,992657,1298248,178.0,43.0
484,2018-11-30,0,1216.827714,126,2966,1.0,0.0,43.0,1,38.0,40.5,3358.0,1100,931232,1115149,163.0,50.0
485,2018-12-03,0,1434.221248,125,3078,0.0,0.0,55.0,0,46.0,50.5,2966.0,1176,984143,1103347,184.0,51.0
486,2018-12-04,1,1775.119740,130,3232,0.0,0.0,46.0,0,31.0,38.5,3078.0,1223,1054844,1276342,187.0,27.0
487,2018-12-05,1,1607.037512,126,3119,0.0,0.0,37.0,0,28.0,32.5,3232.0,1199,954348,1284185,169.0,59.0
488,2018-12-06,1,1556.371753,128,3080,0.0,0.0,40.0,0,30.0,35.0,3119.0,1150,943434,1282307,172.0,53.0
489,2018-12-07,0,1331.167974,129,3060,0.0,0.0,40.0,0,29.0,34.5,3080.0,1154,960872,1129155,170.0,86.0
490,2018-12-10,0,1264.566005,127,2871,0.0,0.0,41.0,0,30.0,35.5,3060.0,1102,937928,1338739,171.0,61.0
491,2018-12-11,1,1795.111660,127,3036,0.0,0.0,43.0,0,31.0,37.0,2871.0,1163,937333,1186407,163.0,125.0
492,2018-12-12,1,1551.491558,136,3139,0.0,0.0,42.0,0,34.0,38.0,3036.0,1155,984158,1322685,188.0,85.0
493,2018-12-13,1,2026.362245,120,3136,0.0,0.0,42.0,0,35.0,38.5,3139.0,1157,1011451,1245801,193.0,55.0
494,2018-12-14,0,1383.718226,124,2864,0.0,0.0,50.0,0,41.0,45.5,3136.0,1098,861987,1203155,163.0,93.0
495,2018-12-17,0,1291.425570,120,2808,0.0,0.0,48.0,0,38.0,43.0,2864.0,1077,897304,1168919,172.0,74.0
496,2018-12-18,1,1743.626011,125,2968,0.0,0.0,40.0,0,29.0,34.5,2808.0,1118,909101,1169714,178.0,57.0
497,2018-12-19,1,1842.445163,127,3246,0.0,0.0,43.0,0,28.0,35.5,2968.0,1169,1070542,1284058,207.0,74.0
498,2018-12-20,1,1786.379916,129,3077,0.0,0.0,54.0,0,35.0,44.5,3246.0,1182,990373,1167756,196.0,69.0
499,2018-12-21,1,1694.999243,119,2642,1.0,0.0,60.0,0,52.0,56.0,3077.0,1042,817394,1329074,174.0,42.0
500,2018-12-24,0,907.955507,105,1843,0.0,0.0,44.0,0,37.0,40.5,2642.0,713,666251,1195274,108.0,26.0
501,2018-12-26,0,943.476654,99,2056,0.0,0.0,44.0,0,33.0,38.5,1843.0,781,626731,1269673,104.0,27.0
502,2018-12-27,0,1377.369615,111,2600,0.0,0.0,46.0,0,39.0,42.5,2056.0,984,797937,1190259,159.0,61.0
503,2018-12-28,0,1420.501332,109,2252,0.0,0.0,58.0,0,44.0,51.0,2600.0,887,699880,1272483,125.0,43.0
504,2018-12-31,0,1306.296117,99,1648,NaN,NaN,NaN,0,NaN,NaN,2252.0,700,586615,1329576,83.0,11.0

In [ ]:
"""
tenPercent = int(0.20*len(df_final))
#validation dataset
df_valid = df_final[(len(df_final) -tenPercent) :]
#train and test dataset
df_train_test = df_final[ : (len(df_final) - tenPercent)]

"""

DETERMINE FEATURE IMPORTANCE USING DECISION TREES

In [187]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from operator import itemgetter

y = df_final["Target"] 
#y = df_train_test["Target"] 
#X = df[["StaffCount", "Trans1DayAgo", "PRCP", "SNOW", "TMAX", "TMIN", "TAVE"]]
X = df_final.drop('Target', 1)
#X = df_train_test.drop('Target', 1)
#X = df_train_test[["StaffCount", "Trans1DayAgo", "PRCP", "SNOW", "TAVE", "TRANSACTION_TIME_mean"]]
    
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                   random_state = 0)
    
X_train = X_train.fillna(X_train.mean())
X_test = X_test.fillna(X_train.mean())



clf = DecisionTreeClassifier(max_depth = 4, min_samples_leaf = 8, random_state = 0).fit(X_train, y_train)
#clf = DecisionTreeClassifier(max_depth = 4, random_state = 0).fit(X_train, y_train)


#plot_decision_tree(clf, cancer.feature_names, cancer.target_names)

print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))


print ("FEATURE IMPORTANCE")
feat_imp = []

#for name, score in zip(data, rnd_clf.feature_importances_):
#    print(name, score)

for name, score in zip(X_train, clf.feature_importances_):
    feat_imp.append([name,score])
    #print(name, score)
    
feat_imp = sorted(feat_imp, key=itemgetter(1), reverse=True)

#print (feat_imp)

for feat in feat_imp:
    print (feat)

Accuracy of Decision Tree classifier on training set: 0.86
Accuracy of Decision Tree classifier on test set: 0.86
FEATURE IMPORTANCE
['SeasonFall', 0.4574139292712725]
['#CUSTOMERS', 0.25372822712554743]
['SC_Fast App', 0.16470996412372294]
['DS_AP - ProCert Filing', 0.1241478794794571]

In [ ]:
df_final.to_csv(path + "test.csv")

In [219]:
df3["#CUSTOMERS"].mean()

1132.491089108911

### MODELING

In [188]:
import pandas as pd
import numpy as np

def QmaticModel(df):
    
    from sklearn.ensemble import GradientBoostingClassifier
    from sklearn.linear_model import LogisticRegression
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.naive_bayes import GaussianNB
    from sklearn.svm import SVC
    from sklearn.ensemble import RandomForestClassifier
    
    from sklearn.model_selection import cross_val_score
    from sklearn import model_selection
    from sklearn.model_selection import KFold
    from sklearn.metrics import make_scorer

    from sklearn.model_selection import train_test_split
    #from adspy_shared_utilities import plot_class_regions_for_classifier_subplot
    #create data
    from sklearn.model_selection import train_test_split
    from sklearn.datasets import make_classification, make_blobs
    from sklearn.dummy import DummyClassifier
    from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
    from sklearn.metrics import classification_report
    from sklearn.metrics import roc_curve, auc
    import seaborn as sns
    import matplotlib.pyplot as plt
    from sklearn.metrics import confusion_matrix
    from sklearn.preprocessing import MinMaxScaler
    from sklearn.metrics import roc_auc_score
    from sklearn.model_selection import GridSearchCV
    
    #df["Trans1DayAgo"] = df["Trans1DayAgo"].fillna(df.Trans1DayAgo.mean())
    
    #y = df["Target"] 
    #X = df[["StaffCount", "Trans1DayAgo", "PRCP", "SNOW", "TMAX", "TMIN", "TAVE"]]
    #X = df[["StaffCount", "Trans1DayAgo", "PRCP", "SNOW", "TAVE", "TRANSACTION_TIME_mean"]]
    
    #X = df[["Trans1DayAgo", "TAVE", "TRANSACTION_TIME_mean"]]
    
    y = df["Target"] 
    X = df.drop('Target', 1)
    
    X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                   random_state = 0)
    
    
    X_train = X_train.fillna(X_train.mean())
    X_test = X_test.fillna(X_train.mean())
    
    
    modelSelection = []
    
    def AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X):
        a = "(" + a + ","
        b = b + ")"
        accuracy_param = a + b
        clf_predicted = clf.predict(X_test)
        #print ("Accuracy parameters", a, b)
        #print('Accuracy on training set: {:.2f}'.format(clf.score(X_train, y_train)))
        #print('Accuracy on test set: {:.2f}'.format(accuracy_score(y_test, clf_predicted)))
        #print('Precision: {:.2f}'.format(precision_score(y_test, clf_predicted)))
        #print('Recall: {:.2f}'.format(recall_score(y_test, clf_predicted)))
        #print('F1: {:.2f}'.format(f1_score(y_test, clf_predicted)))
    
        #print(classification_report(y_test, clf_predicted, target_names=['not 1', '1']))
        
        #y_score_gb = clf.fit(X_train, y_train).decision_function(X_test)
        #fpr_lr, tpr_lr, _ = roc_curve(y_test, y_score_gb)
        #roc_auc_gb = auc(fpr_lr, tpr_lr)
        #print ("AUC:", round(roc_auc_gb, 2))
        
        pred_prob = clf.predict_proba(X_test)[:,1]
        roc=roc_auc_score(y_test, pred_prob)
        #print ('AUC:', round(roc, 2))

        
        #clf_predicted = clf.predict(X_test)
        confusion = confusion_matrix(y_test, clf_predicted)
        #print('Classifier Confusion Matrix\n', confusion)
        #print('Classifier Confusion Matrix\n', confusion[1][0])
        
        true_neg = confusion[0][0]
        true_pos = confusion[1][1]
        false_pos = confusion[0][1]
        false_neg = confusion[1][0]
        #print()
        
        #CROSS VALIDATION ACCURACY
        kfold = model_selection.KFold(n_splits=10, random_state=0)
        cross_val_results = model_selection.cross_val_score(estimator=clf, X=X, y=y, cv=kfold, 
                                                            scoring = make_scorer(accuracy_score))
        #print 'mean accuracy', np.mean(cross_val_results)
        
        
        
        modelSelection.append([model,accuracy_param, np.mean(cross_val_results), clf.score(X_train, y_train), accuracy_score(y_test, clf_predicted),
                               precision_score(y_test, clf_predicted),recall_score(y_test, clf_predicted), 
                                f1_score(y_test, clf_predicted), roc, true_neg, true_pos, false_pos, false_neg])
    
    
    
    
    
    #test baseline using dummy classifier
    dummy_majority = DummyClassifier(strategy = 'most_frequent').fit(X_train, y_train)
    
    print ("Baseline Accuracy: Dummy majority score:", round(dummy_majority.score(X_test, y_test), 2) )
    print ()
    
    #RANDOM FORESTS
    print ("Random Forest")
    clf = RandomForestClassifier(random_state = 0)
    clf.fit(X_train, y_train)
    model = "Random Forest"
    a = "default"
    b = "default"
    AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X)
    
    
    
    print ("Random Forest changing params")
    max_depth_list = [4,5,6,8,10,12,14, 16, 18]
    
    #max_features = sqrt(number of features)
    for max_d in max_depth_list:
        clf = RandomForestClassifier(max_features = 2,max_depth = max_d, random_state = 0)
        clf.fit(X_train, y_train)
        a = "max features:" + str(2)
        b = "max depth:" + str(max_d)
        AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X)
        
    
    #GRADIENT BOOSTED DECISION TREES
    print ("GRADIENT BOOSTED DECISION TREES")
    print ("Gradient boosting default parameters")
    clf = GradientBoostingClassifier(random_state = 0)
    clf.fit(X_train, y_train)
    model = "Gradient Boosted Dec Trees"
    a = "default"
    b = "default"
    AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X)
    #PlotROC(clf, X_test, y_test)
    
    print ()
    print ("Adjusting gradient boosted learning rate and depth")
    learn_rate = [0.01, 0.1, 1]
    max_depth = [2,4,6]
    
    for learn in learn_rate:
        for depth in max_depth:
            clf = GradientBoostingClassifier(learning_rate = learn, max_depth = depth, random_state = 0)
            clf.fit(X_train, y_train)
            a = "learning rate:" + str(learn)
            b = "maximum depth:" + str(depth)
            AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X)
            
    #LOGISTIC REGRESSION
    print ()
    print ("LOGISTIC REGRESSION")
    print ("Default parameters")
    clf = LogisticRegression().fit(X_train, y_train)
    clf.fit(X_train, y_train)
    model = "Logistic Regression"
    a = "default"
    b = "default"
    AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X)
    
    print ()
    print ("Varying regularization c parameter")
    this_C_list = [0.1, 1, 100]
    b = "none"
    for this_C in this_C_list:
        a = "C reg param:" + str(this_C)
        clf = LogisticRegression(C=this_C).fit(X_train, y_train)
        AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X)
            
    #K-NEAREST NEIGHBORS
    print ()
    print ("KNN")
    clf = KNeighborsClassifier(n_neighbors = 5)
    clf.fit(X_train, y_train)
    model = "KNN"
    a = "none"
    b = "none"
    AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X)
    
    print()
    print ("KNN with MinMax Scaling")
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    # we must apply the scaling to the test set that we computed for the training set
    X_test_scaled = scaler.transform(X_test)
    clf = KNeighborsClassifier(n_neighbors = 5)
    clf.fit(X_train_scaled, y_train)
    a = "MinMax Scaled"
    b = "none"
    AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X)
    
    print ("KNN with MinMax Scaling and varying k")
    
    k_list = [2,3,4,5,6,7,8,9,10]
    
    for k in k_list:
        b =  "k=" + str(k)
        clf = KNeighborsClassifier(n_neighbors = k)
        clf.fit(X_train_scaled, y_train)
        AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X)
    

    #NAIVE BAYES
    print ()
    print ("NAIVE BAYES")
    clf = GaussianNB().fit(X_train, y_train)
    model = "Naive Bayes"
    a = "default"
    b = "default"
    AccuracyAndAUC(model, clf, X_test, y_test, a, b, y, X)
    
    print()
    
    #SVM
    print ("SUPPORT VECTOR MACHINES")
    #print ("With default RBF Kernal and MinMax Scaling")
    model = "SVM"
    a = "MinMax Scalaing"
    b = "Grid Search"
    accuracy_param = "(" + a + "," + b + ")"
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    
    print ("SVM with RBF kernal and grid search optimizing for AUC")
    
    clf = SVC(kernel='rbf')
    grid_values = {'gamma': [0.001, 0.01, 0.05, 0.1, 1, 10, 100]}
    
    grid_clf_auc = GridSearchCV(clf, param_grid = grid_values, scoring = 'roc_auc')
    grid_clf_auc.fit(X_train_scaled, y_train)
    y_decision_fn_scores_auc = grid_clf_auc.decision_function(X_test_scaled) 

    print('Test set AUC: ', roc_auc_score(y_test, y_decision_fn_scores_auc))
    print('Grid best parameter (max. AUC): ', grid_clf_auc.best_params_)
    print('Grid best score (AUC): ', grid_clf_auc.best_score_)
    
   
        
    modelSelection.append([model,accuracy_param, 0,0, grid_clf_auc.best_score_,
                               0, 0, 0, roc_auc_score(y_test, y_decision_fn_scores_auc), 0, 0, 0, 0])
    

    
    return modelSelection
    
    
#results = QmaticModel(df2)
#results = QmaticModel(df_train_test)
results = QmaticModel(df_final)

#true_neg, true_pos, false_pos, false_neg

results = pd.DataFrame(results, columns=('Model','Parameters','Cross Valid Accuracy', 'Training Accuracy', 
                                         'Test Accuracy', 'Precision', 'Recall', 'F1', 'AUC',
                                         'True Negative', 'True Positive', 'False Positive', 'False Negative'))
#df.to_csv(path + "train_edit.csv", index=False)

results = results.round(3)
#results["Training Accuracy"] = results["Training Accuracy"].round(3)

('Baseline Accuracy: Dummy majority score:', 0.8)
()
Random Forest
Random Forest changing params
GRADIENT BOOSTED DECISION TREES
Gradient boosting default parameters
()
Adjusting gradient boosted learning rate and depth
()
LOGISTIC REGRESSION
Default parameters
()
Varying regularization c parameter
()
KNN
()
KNN with MinMax Scaling
KNN with MinMax Scaling and varying k
()
NAIVE BAYES
()
SUPPORT VECTOR MACHINES
SVM with RBF kernal and grid search optimizing for AUC
('Test set AUC: ', 0.82823529411764707)
('Grid best parameter (max. AUC): ', {'gamma': 0.01})
('Grid best score (AUC): ', 0.80699669966996701)

In [ ]:
results = results.fillna(0)

In [215]:
results

,Model,Parameters,Cross Valid Accuracy,Training Accuracy,Test Accuracy,Precision,Recall,F1,AUC,True Negative,True Positive,False Positive,False Negative
0,Random Forest,"(default,default)",0.816,0.971,0.866,0.750,0.48,0.585,0.753,98,12,4,13
1,Random Forest,"(max features:2,max depth:4)",0.832,0.860,0.850,0.714,0.40,0.513,0.817,98,10,4,15
2,Random Forest,"(max features:2,max depth:5)",0.822,0.892,0.866,0.786,0.44,0.564,0.787,99,11,3,14
3,Random Forest,"(max features:2,max depth:6)",0.834,0.905,0.858,0.706,0.48,0.571,0.810,97,12,5,13
4,Random Forest,"(max features:2,max depth:8)",0.820,0.950,0.866,0.786,0.44,0.564,0.777,99,11,3,14
5,Random Forest,"(max features:2,max depth:10)",0.808,0.955,0.819,0.562,0.36,0.439,0.741,95,9,7,16
6,Random Forest,"(max features:2,max depth:12)",0.810,0.974,0.858,0.706,0.48,0.571,0.764,97,12,5,13
7,Random Forest,"(max features:2,max depth:14)",0.818,0.971,0.866,0.750,0.48,0.585,0.756,98,12,4,13
8,Random Forest,"(max features:2,max depth:16)",0.814,0.971,0.866,0.750,0.48,0.585,0.753,98,12,4,13
9,Random Forest,"(max features:2,max depth:18)",0.816,0.971,0.866,0.750,0.48,0.585,0.753,98,12,4,13
10,Gradient Boosted Dec Trees,"(default,default)",0.816,0.950,0.858,0.818,0.36,0.500,0.747,100,9,2,16
11,Gradient Boosted Dec Trees,"(learning rate:0.01,maximum depth:2)",0.820,0.831,0.835,1.000,0.16,0.276,0.824,102,4,0,21
12,Gradient Boosted Dec Trees,"(learning rate:0.01,maximum depth:4)",0.834,0.881,0.843,0.857,0.24,0.375,0.811,101,6,1,19
13,Gradient Boosted Dec Trees,"(learning rate:0.01,maximum depth:6)",0.816,0.926,0.850,0.875,0.28,0.424,0.778,101,7,1,18
14,Gradient Boosted Dec Trees,"(learning rate:0.1,maximum depth:2)",0.822,0.897,0.835,0.700,0.28,0.400,0.791,99,7,3,18
15,Gradient Boosted Dec Trees,"(learning rate:0.1,maximum depth:4)",0.796,0.995,0.811,0.533,0.32,0.400,0.737,95,8,7,17
16,Gradient Boosted Dec Trees,"(learning rate:0.1,maximum depth:6)",0.781,1.000,0.795,0.471,0.32,0.381,0.718,93,8,9,17
17,Gradient Boosted Dec Trees,"(learning rate:1,maximum depth:2)",0.789,1.000,0.772,0.400,0.32,0.356,0.704,90,8,12,17
18,Gradient Boosted Dec Trees,"(learning rate:1,maximum depth:4)",0.798,1.000,0.780,0.421,0.32,0.364,0.707,91,8,11,17
19,Gradient Boosted Dec Trees,"(learning rate:1,maximum depth:6)",0.782,1.000,0.787,0.429,0.24,0.308,0.742,94,6,8,19
20,Logistic Regression,"(default,default)",0.826,0.831,0.811,0.571,0.16,0.250,0.816,99,4,3,21
21,Logistic Regression,"(C reg param:0.1,none)",0.814,0.817,0.811,0.667,0.08,0.143,0.782,101,2,1,23
22,Logistic Regression,"(C reg param:1,none)",0.826,0.831,0.811,0.571,0.16,0.250,0.816,99,4,3,21
23,Logistic Regression,"(C reg param:100,none)",0.830,0.839,0.858,0.733,0.44,0.550,0.837,98,11,4,14
24,KNN,"(none,none)",0.820,0.860,0.819,0.625,0.20,0.303,0.614,99,5,3,20
25,KNN,"(MinMax Scaled,none)",0.820,0.198,0.197,0.197,1.00,0.329,0.500,0,25,102,0
26,KNN,"(MinMax Scaled,k=2)",0.806,0.198,0.197,0.197,1.00,0.329,0.500,0,25,102,0
27,KNN,"(MinMax Scaled,k=3)",0.808,0.198,0.197,0.197,1.00,0.329,0.500,0,25,102,0
28,KNN,"(MinMax Scaled,k=4)",0.828,0.198,0.197,0.197,1.00,0.329,0.500,0,25,102,0
29,KNN,"(MinMax Scaled,k=5)",0.820,0.198,0.197,0.197,1.00,0.329,0.500,0,25,102,0
30,KNN,"(MinMax Scaled,k=6)",0.820,0.198,0.197,0.197,1.00,0.329,0.500,0,25,102,0
31,KNN,"(MinMax Scaled,k=7)",0.820,0.198,0.197,0.197,1.00,0.329,0.500,0,25,102,0
32,KNN,"(MinMax Scaled,k=8)",0.816,0.198,0.197,0.197,1.00,0.329,0.500,0,25,102,0
33,KNN,"(MinMax Scaled,k=9)",0.812,0.198,0.197,0.197,1.00,0.329,0.500,0,25,102,0
34,KNN,"(MinMax Scaled,k=10)",0.818,0.198,0.197,0.197,1.00,0.329,0.500,0,25,102,0
35,Naive Bayes,"(default,default)",0.814,0.839,0.850,0.688,0.44,0.537,0.809,97,11,5,14
36,SVM,"(MinMax Scalaing,Grid Search)",0.000,0.000,0.807,0.000,0.00,0.000,0.828,0,0,0,0

In [217]:
results.to_csv(path + "results_data_all_continuous target=20min 1.csv")

### STANDARD LOGISTIC REGRESSION

In [205]:
import statsmodels.api as sm
import numpy as np

df_finalLog = df3.copy()

#INITIAL MODEL

#modelLog = ["Target", "TAVE", "SNOW", "PRCP", "Trans", "Trans1DayAgo", "StaffCount", "#CUSTOMERS", "SeasonFall",
#          "SERVING_TIME", "IDLE_TIME", "SC_Fast App",  'DS_AP - ProCert Filing']

#df_finalLog = df_finalLog[modelLog]

#FINAL MODEL

modelLog = ["Target", "TAVE", "Trans", "StaffCount", "#CUSTOMERS", "SeasonFall", "SC_Fast App",  'DS_AP - ProCert Filing']

df_finalLog = df_finalLog[modelLog]




print "drop NaN", len(df_final)
df_finalLog = df_finalLog.dropna()
print "after drop", len(df_final)


y = df_finalLog["Target"] 

X = df_finalLog.drop('Target', 1)



logit_model=sm.Logit(y,X)
logitResult=logit_model.fit()
print(logitResult.summary())
#print
#print "ODDS RATIOS"
#print np.exp(logitResult.params)
print
print "Odds ratio and Confidence Intervals"
params = logitResult.params
conf = logitResult.conf_int()
conf['OR'] = params
conf.columns = ['2.5%', '97.5%', 'Odds Ratio']
print(np.exp(conf))

drop NaN 505
after drop 505
Optimization terminated successfully.
         Current function value: 0.339728
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                 Target   No. Observations:                  504
Model:                          Logit   Df Residuals:                      497
Method:                           MLE   Df Model:                            6
Date:                Wed, 16 Jan 2019   Pseudo R-squ.:                  0.3181
Time:                        13:29:10   Log-Likelihood:                -171.22
converged:                       True   LL-Null:                       -251.09
                                        LLR p-value:                 6.744e-32
==========================================================================================
                             coef    std err          z      P>|z|      [95.0% Conf. Int.]
------------------------------------------------------------------------------------------
TAVE                      -0.0216      0.010     -2.210      0.027        -0.041    -0.002
Trans                     -0.0050      0.001     -4.085      0.000        -0.007    -0.003
StaffCount                -0.1119      0.020     -5.645      0.000        -0.151    -0.073
#CUSTOMERS                 0.0204      0.004      4.964      0.000         0.012     0.029
SeasonFall                 2.1035      0.299      7.032      0.000         1.517     2.690
SC_Fast App                0.0245      0.008      2.933      0.003         0.008     0.041
DS_AP - ProCert Filing     0.0228      0.007      3.225      0.001         0.009     0.037
==========================================================================================

Odds ratio and Confidence Intervals
                            2.5%      97.5%  Odds Ratio
TAVE                    0.960086   0.997565    0.978646
Trans                   0.992693   0.997425    0.995056
StaffCount              0.860102   0.929577    0.894165
#CUSTOMERS              1.012445   1.028917    1.020648
SeasonFall              4.559503  14.728976    8.194925
SC_Fast App             1.008156   1.041695    1.024788
DS_AP - ProCert Filing  1.008983   1.037326    1.023056

In [198]:
X

,TAVE,SNOW,PRCP,Trans,Trans1DayAgo,StaffCount,#CUSTOMERS,SeasonFall,SERVING_TIME,IDLE_TIME,SC_Fast App,DS_AP - ProCert Filing
0,66.0,0.0,0.0,2745,2745.0,126,977,1,1085333,1797083,146.0,57.0
1,64.5,0.0,0.0,2371,2745.0,119,929,1,3016194,4214952,108.0,34.0
2,60.0,0.0,0.0,2123,2371.0,124,830,1,1466052,3841504,107.0,55.0
3,64.0,0.0,0.0,2973,2123.0,128,1117,1,903961,1629441,122.0,55.0
4,66.0,0.0,0.0,3355,2973.0,125,1158,1,1294825,1710081,172.0,73.0
5,54.5,0.0,0.0,2802,3355.0,134,1091,1,1569910,2642844,172.0,60.0
6,59.5,0.0,0.0,2427,2802.0,123,973,1,864970,1780717,107.0,50.0
7,60.0,0.0,0.0,3351,2427.0,137,1205,1,1126039,1929345,170.0,82.0
8,54.5,0.0,0.0,3415,3351.0,135,1181,1,1514061,3891612,206.0,72.0
9,72.0,0.0,0.0,2751,3415.0,121,1070,1,1060196,1772317,112.0,61.0
10,74.0,0.0,0.0,3423,2751.0,143,1214,1,1143652,1720066,159.0,74.0
11,75.0,0.0,0.0,3310,3423.0,128,1163,1,1268273,2051380,175.0,93.0
12,66.0,0.0,0.0,3194,3310.0,131,1138,1,1294260,3143692,196.0,75.0
13,63.0,0.0,1.0,3034,3194.0,132,1106,1,1410275,2650619,152.0,75.0
14,54.5,0.0,0.0,2978,3034.0,122,1076,1,1077490,1672260,163.0,49.0
15,47.5,0.0,0.0,3330,2978.0,137,1181,1,1209116,1906537,170.0,86.0
16,44.5,0.0,0.0,3266,3330.0,139,1173,1,1179670,2041439,155.0,75.0
17,47.5,0.0,1.0,3485,3266.0,135,1202,1,1176138,2138475,159.0,76.0
18,46.5,0.0,0.0,3284,3485.0,131,1182,1,1135124,2004484,178.0,61.0
19,49.0,0.0,0.0,2807,3284.0,133,1057,1,1022786,2139494,126.0,33.0
20,49.0,0.0,0.0,3392,2807.0,137,1195,1,1154476,1797169,157.0,46.0
21,62.0,0.0,0.0,3457,3392.0,136,1217,1,1187065,1894628,190.0,50.0
22,64.5,0.0,0.0,3384,3457.0,132,1201,1,1133340,1751557,185.0,61.0
23,54.0,0.0,0.0,3454,3384.0,130,1226,1,1160054,1951990,178.0,58.0
24,47.0,0.0,0.0,3458,3454.0,127,1214,1,1189990,2082959,193.0,67.0
25,54.0,0.0,1.0,4154,3458.0,144,1377,1,1350571,2048696,271.0,59.0
26,48.0,0.0,0.0,4053,4154.0,135,1364,1,1372383,1926745,239.0,77.0
27,54.0,0.0,0.0,4023,4053.0,138,1330,1,1254929,1894650,229.0,71.0
28,51.5,0.0,1.0,3690,4023.0,134,1204,1,1239517,2057745,200.0,47.0
29,53.0,0.0,0.0,3795,3690.0,136,1340,1,1335674,1921003,182.0,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...
475,39.5,0.0,1.0,2756,3389.0,124,1044,1,860433,1256972,179.0,28.0
476,45.5,0.0,0.0,3379,2756.0,137,1255,1,1026088,1332609,174.0,26.0
477,43.0,0.0,0.0,3403,3379.0,131,1242,1,1113004,1293803,174.0,24.0
478,35.5,0.0,0.0,3099,3403.0,129,1150,1,1001231,1183912,193.0,34.0
479,23.5,0.0,0.0,1406,3099.0,94,558,1,516511,1156345,76.0,14.0
480,49.0,0.0,1.0,2731,1406.0,128,1024,1,758742,1364360,126.0,4.0
481,41.0,0.0,1.0,3216,2731.0,125,1159,1,970324,1184020,187.0,26.0
482,39.0,0.0,0.0,3348,3216.0,133,1212,1,1024227,1277462,166.0,49.0
483,42.0,0.0,0.0,3358,3348.0,133,1236,1,992657,1298248,178.0,43.0
484,40.5,0.0,1.0,2966,3358.0,126,1100,1,931232,1115149,163.0,50.0
485,50.5,0.0,0.0,3078,2966.0,125,1176,0,984143,1103347,184.0,51.0
486,38.5,0.0,0.0,3232,3078.0,130,1223,0,1054844,1276342,187.0,27.0
487,32.5,0.0,0.0,3119,3232.0,126,1199,0,954348,1284185,169.0,59.0
488,35.0,0.0,0.0,3080,3119.0,128,1150,0,943434,1282307,172.0,53.0
489,34.5,0.0,0.0,3060,3080.0,129,1154,0,960872,1129155,170.0,86.0
490,35.5,0.0,0.0,2871,3060.0,127,1102,0,937928,1338739,171.0,61.0
491,37.0,0.0,0.0,3036,2871.0,127,1163,0,937333,1186407,163.0,125.0
492,38.0,0.0,0.0,3139,3036.0,136,1155,0,984158,1322685,188.0,85.0
493,38.5,0.0,0.0,3136,3139.0,120,1157,0,1011451,1245801,193.0,55.0
494,45.5,0.0,0.0,2864,3136.0,124,1098,0,861987,1203155,163.0,93.0
495,43.0,0.0,0.0,2808,2864.0,120,1077,0,897304,1168919,172.0,74.0
496,34.5,0.0,0.0,2968,2808.0,125,1118,0,909101,1169714,178.0,57.0
497,35.5,0.0,0.0,3246,2968.0,127,1169,0,1070542,1284058,207.0,74.0
498,44.5,0.0,0.0,3077,3246.0,129,1182,0,990373,1167756,196.0,69.0
499,56.0,0.0,1.0,2642,3077.0,119,1042,0,817394,1329074,174.0,42.0
500,40.5,0.0,0.0,1843,2642.0,105,713,0,666251,1195274,108.0,26.0
501,38.5,0.0,0.0,2056,1843.0,99,781,0,626731,1269673,104.0,27.0
502,42.5,0.0,0.0,2600,2056.0,111,984,0,797937,1190259,159.0,61.0
503,51.0,0.0,0.0,2252,2600.0,109,887,0,699880,1272483,125.0,43.0
504,NaN,NaN,NaN,1648,2252.0,99,700,0,586615,1329576,83.0,11.0

In [214]:
#from sklearn.datasets import make_classification
#X, y = make_classification(n_samples=5000, n_features=2, n_informative=2,
                            n_redundant=0, n_repeated=0, n_classes=3,
                            n_clusters_per_class=1,
                            weights=[0.01, 0.05, 0.94],
                            class_sep=0.8, random_state=0)

#print y

#from imblearn.over_sampling import RandomOverSampler
#ros = RandomOverSampler(random_state=0)
#X_resampled, y_resampled = ros.fit_resample(X, y)
#from collections import Counter
#print(sorted(Counter(y_resampled).items()))
[(0, 4674), (1, 4674), (2, 4674)]

IndentationError: unexpected indent (<ipython-input-214-d08f7c4bd4b7>, line 3)

### PREDICTING PROB ON BEST MODEL

In [ ]:
def best_model(df_valid, df_train_test):
    
    from sklearn.ensemble import GradientBoostingClassifier
    from sklearn.linear_model import LogisticRegression
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.naive_bayes import GaussianNB
    from sklearn.svm import SVC
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.preprocessing import MinMaxScaler

    
    test = df_valid.copy()
    train = df_train_test.copy()
    
    
    #TRAIN AND TEST THE MODEL
    #y_train = df_train_test["Target"]
    #X_train = df_train_test[["StaffCount", "Trans1DayAgo", "PRCP", "SNOW", "TAVE", "TRANSACTION_TIME_mean"]]
    #X_train = df_train_test[["Trans1DayAgo", "TAVE", "TRANSACTION_TIME_mean"]]
    
    
    y_train = df_train_test["Target"] 
    X_train = df_train_test.drop('Target', 1)
    
    
    #y_test = df_valid["Target"]
    #X_test = df_valid[["StaffCount", "Trans1DayAgo", "PRCP", "SNOW", "TAVE", "TRANSACTION_TIME_mean"]]
    #X_test = df_valid[["Trans1DayAgo", "TAVE", "TRANSACTION_TIME_mean"]]
    
    y_test = df_valid["Target"] 
    X_test = df_valid.drop('Target', 1)
    
    
 
    X_train = X_train.fillna(X_train.mean())
    X_test = X_test.fillna(X_train.mean())
    
    """
    #K-NEAREST NEIGHBORS
    print ("KNN with MinMax Scaling")
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    # we must apply the scaling to the test set that we computed for the training set
    X_test_scaled = scaler.transform(X_test)
    clf = KNeighborsClassifier(n_neighbors = 4)
    clf.fit(X_train_scaled, y_train)
    """
    
    #clf = GradientBoostingClassifier(learning_rate = 0.01, max_depth = 2, random_state = 0)
    #clf = GradientBoostingClassifier(learning_rate = 0.1, max_depth = 2, random_state = 0)

    
    #clf = GradientBoostingClassifier(random_state = 0)
    #clf.fit(X_train, y_train)
    
    clf = RandomForestClassifier(max_features = 2,max_depth = 5, random_state = 0)
    
    #clf = SVC(kernel='rbf')
    
    #clf = GaussianNB().fit(X_train, y_train)
    clf.fit(X_train, y_train)
    
    #predict probabilities
    result  =   clf.predict_proba(X_test)
    #assign positive class probability predictions
    test["PredProb"] = result[:,1]
    
    #prediction
    test["Prediction"] = clf.predict(X_test)
    
    #test["PredProb"] = result[0]
    
    return test


best = best_model(df_valid, df_train_test)

best = best.sort_values(by = 'Target', ascending=False).reset_index(drop=True)

In [ ]:
best

In [ ]:
best.to_csv(path + "predictied probabilities2.csv")